// SWADE Character Creation Data
// All game data for Savage Worlds Adventure Edition

const SWADE = {
  DIE_TYPES: [4, 6, 8, 10, 12],
  RANKS: ['Novice', 'Seasoned', 'Veteran', 'Heroic', 'Legendary'],

  ATTRIBUTES: [
    { id: 'agility', name: 'Agility', description: 'Nimbleness, dexterity, and overall physical coordination.' },
    { id: 'smarts', name: 'Smarts', description: 'Raw intellect, mental acuity, and ability to process information.' },
    { id: 'spirit', name: 'Spirit', description: 'Inner strength, willpower, and force of personality.' },
    { id: 'strength', name: 'Strength', description: 'Raw physical power and fitness.' },
    { id: 'vigor', name: 'Vigor', description: 'Endurance, hardiness, and resistance to disease and toxins.' },
  ],

  SKILLS: [
    // Core Skills (start at d4 for free)
    { id: 'athletics', name: 'Athletics', attribute: 'agility', core: true, description: 'Running, jumping, climbing, swimming, throwing, catching.' },
    { id: 'commonKnowledge', name: 'Common Knowledge', attribute: 'smarts', core: true, description: 'General knowledge of the setting and culture.' },
    { id: 'notice', name: 'Notice', attribute: 'smarts', core: true, description: 'Awareness and perception, spotting clues and danger.' },
    { id: 'persuasion', name: 'Persuasion', attribute: 'spirit', core: true, description: 'Convincing others through charm, negotiation, or deception.' },
    { id: 'stealth', name: 'Stealth', attribute: 'agility', core: true, description: 'Sneaking, hiding, and avoiding detection.' },

    // Other Skills
    { id: 'academics', name: 'Academics', attribute: 'smarts', core: false, description: 'Knowledge of liberal arts, humanities, and social sciences.' },
    { id: 'battle', name: 'Battle', attribute: 'smarts', core: false, description: 'Military strategy and tactical knowledge for Mass Battles.' },
    { id: 'boating', name: 'Boating', attribute: 'agility', core: false, description: 'Operating and maneuvering boats and ships.' },
    { id: 'driving', name: 'Driving', attribute: 'agility', core: false, description: 'Operating ground vehicles.' },
    { id: 'electronics', name: 'Electronics', attribute: 'smarts', core: false, description: 'Using and repairing electronic devices.' },
    { id: 'faith', name: 'Faith', attribute: 'spirit', core: false, arcane: 'miracles', description: 'Arcane skill for Arcane Background (Miracles).' },
    { id: 'fighting', name: 'Fighting', attribute: 'agility', core: false, description: 'Melee combat skill covering all hand-to-hand weapons.' },
    { id: 'focus', name: 'Focus', attribute: 'spirit', core: false, arcane: 'gifted', description: 'Arcane skill for Arcane Background (Gifted).' },
    { id: 'gambling', name: 'Gambling', attribute: 'smarts', core: false, description: 'Playing and cheating at games of chance.' },
    { id: 'hacking', name: 'Hacking', attribute: 'smarts', core: false, description: 'Breaking into computer systems.' },
    { id: 'healing', name: 'Healing', attribute: 'smarts', core: false, description: 'Treating injuries, diseases, and poisons.' },
    { id: 'intimidation', name: 'Intimidation', attribute: 'spirit', core: false, description: 'Frightening opponents through threats or menace.' },
    { id: 'language', name: 'Language', attribute: 'smarts', core: false, description: 'Knowledge of additional languages.' },
    { id: 'occult', name: 'Occult', attribute: 'smarts', core: false, description: 'Knowledge of supernatural lore and creatures.' },
    { id: 'performance', name: 'Performance', attribute: 'spirit', core: false, description: 'Singing, dancing, acting, and other performing arts.' },
    { id: 'piloting', name: 'Piloting', attribute: 'agility', core: false, description: 'Operating aircraft and spacecraft.' },
    { id: 'psionics', name: 'Psionics', attribute: 'smarts', core: false, arcane: 'psionics', description: 'Arcane skill for Arcane Background (Psionics).' },
    { id: 'repair', name: 'Repair', attribute: 'smarts', core: false, description: 'Fixing mechanical and electrical devices.' },
    { id: 'research', name: 'Research', attribute: 'smarts', core: false, description: 'Finding information from libraries, databases, or the internet.' },
    { id: 'riding', name: 'Riding', attribute: 'agility', core: false, description: 'Riding horses, dragons, or other mounts.' },
    { id: 'science', name: 'Science', attribute: 'smarts', core: false, description: 'Knowledge of natural and physical sciences.' },
    { id: 'shooting', name: 'Shooting', attribute: 'agility', core: false, description: 'Ranged combat with guns, bows, crossbows, etc.' },
    { id: 'spellcasting', name: 'Spellcasting', attribute: 'smarts', core: false, arcane: 'magic', description: 'Arcane skill for Arcane Background (Magic).' },
    { id: 'survival', name: 'Survival', attribute: 'smarts', core: false, description: 'Tracking, foraging, and navigating in the wild.' },
    { id: 'taunt', name: 'Taunt', attribute: 'smarts', core: false, description: 'Insulting and provoking opponents.' },
    { id: 'thievery', name: 'Thievery', attribute: 'agility', core: false, description: 'Picking locks, picking pockets, sleight of hand.' },
    { id: 'weirdScience', name: 'Weird Science', attribute: 'smarts', core: false, arcane: 'weirdScience', description: 'Arcane skill for Arcane Background (Weird Science).' },
  ],

  RACES: [
    {
      id: 'human', name: 'Human',
      description: 'Humans are the most adaptable and ambitious of all races. They receive one free Edge of their choice.',
      abilities: [
        { type: 'free_edge', count: 1, label: 'Adaptable', description: 'Humans begin with any one free Novice Edge of their choosing. They must meet its Requirements as usual.' },
      ],
    },
    {
      id: 'android', name: 'Android',
      description: 'Artificial beings built to serve, now self-aware and seeking their place in the world.',
      abilities: [
        { type: 'ability', label: 'Construct', description: '+2 to recover from Shaken; ignores 1 point of Wound modifiers; immune to disease and poison; does not heal naturally (requires Repair skill).' },
        { type: 'racial_hindrance', label: 'Outsider (Major)', description: 'Treated with suspicion. -2 Persuasion with most living beings.' },
        { type: 'racial_hindrance', label: 'Vow (Major)', description: 'Programmed with a major directive.' },
        { type: 'free_skills', skills: [{ pick: 2, linkedTo: 'any', value: 6 }], label: 'Programming', description: 'Begins with d6 in two skills of their choice (representing their programming).' },
      ],
    },
    {
      id: 'aquarian', name: 'Aquarian',
      description: 'Aquatic beings equally at home above or below the waves.',
      abilities: [
        { type: 'ability', label: 'Aquatic', description: 'Swim Pace equal to Swimming skill. Cannot drown in water.' },
        { type: 'toughness_bonus', value: 1, label: 'Tough', description: '+1 Toughness from tough skin or scales.' },
        { type: 'racial_hindrance', label: 'Dependency (Water)', description: 'Must immerse in water one hour per day or become Fatigued (each day until Incapacitated).' },
        { type: 'pace_modifier', value: -1, label: 'Aquatic Build', description: 'Pace 5 on land due to fins/webbed feet. d4 running die.' },
        { type: 'run_die', value: 4 },
      ],
    },
    {
      id: 'avion', name: 'Avion',
      description: 'Winged humanoids who soar through the skies.',
      abilities: [
        { type: 'ability', label: 'Flight', description: 'Flying Pace of 12, Climb 0. Cannot fly if encumbered or in more than light armor.' },
        { type: 'toughness_bonus', value: -1, label: 'Frail', description: '-1 Toughness due to hollow bones.' },
        { type: 'ability', label: 'Keen Senses', description: '+2 to Notice rolls.' },
        { type: 'racial_hindrance', label: 'Can\'t Swim', description: 'Wings make swimming extremely difficult.' },
      ],
    },
    {
      id: 'dwarf', name: 'Dwarf',
      description: 'Stout, tough folk who excel in craftsmanship and have an affinity for the underground.',
      abilities: [
        { type: 'ability', label: 'Low Light Vision', description: 'Can see in dim and dark conditions (ignore penalties for Dim and Dark lighting).' },
        { type: 'pace_set', value: 5, label: 'Reduced Pace', description: 'Pace 5 and d4 running die due to short legs.' },
        { type: 'run_die', value: 4 },
        { type: 'attribute_minimum', attribute: 'vigor', value: 6, label: 'Tough', description: 'Dwarves start with d6 Vigor instead of d4.' },
      ],
    },
    {
      id: 'elf', name: 'Elf',
      description: 'Graceful and long-lived, elves are agile and perceptive but struggle with mechanical devices.',
      abilities: [
        { type: 'attribute_minimum', attribute: 'agility', value: 6, label: 'Agile', description: 'Elves start with d6 Agility instead of d4.' },
        { type: 'racial_hindrance', label: 'All Thumbs', description: '-2 to use mechanical and electronic devices.' },
        { type: 'ability', label: 'Low Light Vision', description: 'Can see in dim and dark conditions (ignore penalties for Dim and Dark lighting).' },
      ],
    },
    {
      id: 'halfElf', name: 'Half-Elf',
      description: 'Born of two worlds, half-elves inherit traits from both human and elven parents.',
      abilities: [
        { type: 'ability', label: 'Low Light Vision', description: 'Can see in dim and dark conditions (ignore penalties for Dim and Dark lighting).' },
        { type: 'racial_hindrance', label: 'Outsider (Minor)', description: 'Caught between two worlds. -2 Persuasion with all but own kind.' },
        { type: 'heritage_choice', label: 'Heritage', description: 'Choose one: Adaptable (one free Novice Edge, as Human) or Agile (d6 Agility, as Elf).',
          choices: [
            { id: 'adaptable', name: 'Adaptable (Human Heritage)', effects: [{ type: 'free_edge', count: 1 }] },
            { id: 'agile', name: 'Agile (Elven Heritage)', effects: [{ type: 'attribute_minimum', attribute: 'agility', value: 6 }] },
          ]
        },
      ],
    },
    {
      id: 'halfFolk', name: 'Half-Folk',
      description: 'Small but spirited folk known for their luck, courage, and love of comfort.',
      abilities: [
        { type: 'attribute_minimum', attribute: 'spirit', value: 6, label: 'Spirited', description: 'Half-Folk start with d6 Spirit instead of d4.' },
        { type: 'pace_set', value: 5, label: 'Reduced Pace', description: 'Pace 5 and d4 running die due to short legs.' },
        { type: 'run_die', value: 4 },
        { type: 'size_modifier', value: -1, label: 'Size -1', description: 'Half-Folk average about 4\' tall. Size -1 and -1 Toughness.' },
        { type: 'free_edge_specific', edge: 'luck', label: 'Lucky', description: 'Half-Folk draw one extra Benny per session.' },
      ],
    },
    {
      id: 'rakashan', name: 'Rakashan',
      description: 'Feline humanoids with keen senses, sharp claws, and predatory instincts.',
      abilities: [
        { type: 'attribute_minimum', attribute: 'agility', value: 6, label: 'Agile', description: 'Rakashans start with d6 Agility.' },
        { type: 'ability', label: 'Bite/Claws', description: 'Str+d4 natural weapons.' },
        { type: 'ability', label: 'Low Light Vision', description: 'Can see in dim and dark conditions.' },
        { type: 'racial_hindrance', label: 'Bloodthirsty (Major)', description: 'Rakashans are fierce and rarely take prisoners. -4 Charisma among civilized races.' },
        { type: 'racial_hindrance', label: 'Can\'t Swim', description: 'Rakashans are not natural swimmers. -2 to Athletics (swimming) and begin drowning if they fail.' },
      ],
    },
    {
      id: 'saurian', name: 'Saurian',
      description: 'Lizard-folk with tough scales and powerful jaws, but cold-blooded and seen as outsiders.',
      abilities: [
        { type: 'attribute_minimum', attribute: 'strength', value: 6, label: 'Strong', description: 'Saurians start with d6 Strength.' },
        { type: 'ability', label: 'Natural Armor (+2)', description: 'Thick scales grant +2 Armor.' },
        { type: 'ability', label: 'Bite', description: 'Str+d6 bite attack.' },
        { type: 'ability', label: 'Environmental Weakness (Cold)', description: '-4 to resist cold environmental effects. Take +4 damage from cold-based attacks.' },
        { type: 'racial_hindrance', label: 'Outsider (Major)', description: 'Saurians are distrusted by most. -2 Persuasion with non-Saurians.' },
      ],
    },
  ],

  HINDRANCES: [
    // Minor Hindrances
    { id: 'allThumbs', name: 'All Thumbs', type: 'Minor', description: '-2 to use mechanical or electrical devices. Cause a malfunction on a Critical Failure with such devices.' },
    { id: 'anemic', name: 'Anemic', type: 'Minor', description: '-2 to Vigor rolls to resist Fatigue from cold, disease, drowning, heat, poison, and radiation.' },
    { id: 'cantSwim', name: "Can't Swim", type: 'Minor', description: '-2 to Athletics (swimming) rolls. Each pointed inch of water counts as Difficult Terrain.' },
    { id: 'cautious', name: 'Cautious', type: 'Minor', description: 'Character is overly careful. The player must describe precautions taken in every dangerous situation.' },
    { id: 'deathWish', name: 'Death Wish', type: 'Minor', description: 'The hero wants to die fighting for a cause, finishing a quest, etc.' },
    { id: 'delusionalMinor', name: 'Delusional (Minor)', type: 'Minor', description: 'The character believes something strange that causes occasional problems.' },
    { id: 'doubtingThomas', name: 'Doubting Thomas', type: 'Minor', description: 'Character doesn\'t believe in the supernatural and rationalizes everything.' },
    { id: 'drivenMinor', name: 'Driven (Minor)', type: 'Minor', description: 'The character has a personal goal that occasionally puts them at risk.' },
    { id: 'enemyMinor', name: 'Enemy (Minor)', type: 'Minor', description: 'The character has a recurring enemy of some import.' },
    { id: 'greedyMinor', name: 'Greedy (Minor)', type: 'Minor', description: 'The character argues for a greater share of the loot and tries to get the best deals.' },
    { id: 'habitMinor', name: 'Habit (Minor)', type: 'Minor', description: 'An annoying but gray habit (e.g., constantly cracking knuckles, bad jokes). -1 to Persuasion with those who find it annoying.' },
    { id: 'hardOfHearingMinor', name: 'Hard of Hearing (Minor)', type: 'Minor', description: '-4 to Notice rolls based on sounds.' },
    { id: 'hesitant', name: 'Hesitant', type: 'Minor', description: 'Draw two Action Cards and act on the worst.' },
    { id: 'illiterate', name: 'Illiterate', type: 'Minor', description: 'Cannot read or write. Cannot attempt Academics or Research that requires literacy.' },
    { id: 'impulsive', name: 'Impulsive', type: 'Minor', description: 'The hero acts before thinking, blurting out secrets, attacking without assessing, etc.' },
    { id: 'jealousMinor', name: 'Jealous (Minor)', type: 'Minor', description: 'The character envies those who seem better off.' },
    { id: 'loyal', name: 'Loyal', type: 'Minor', description: 'The character will never leave a companion behind or betray a friend.' },
    { id: 'mean', name: 'Mean', type: 'Minor', description: '-1 to Persuasion due to a pointed, pointed disposition.' },
    { id: 'mildMannered', name: 'Mild Mannered', type: 'Minor', description: '-2 to Intimidation rolls.' },
    { id: 'obligationMinor', name: 'Obligation (Minor)', type: 'Minor', description: 'The character has a duty that demands some of their time.' },
    { id: 'outsiderMinor', name: 'Outsider (Minor)', type: 'Minor', description: 'The character doesn\'t fit in with the dominant culture. -2 Persuasion among those who distrust them.' },
    { id: 'phobiaMinor', name: 'Phobia (Minor)', type: 'Minor', description: '-1 to all Trait rolls when facing the source of fear.' },
    { id: 'poverty', name: 'Poverty', type: 'Minor', description: 'Half starting funds. Struggles to maintain even a modest lifestyle.' },
    { id: 'quirk', name: 'Quirk', type: 'Minor', description: 'A minor behavioral oddity that is mostly harmless but can cause occasional complications.' },
    { id: 'ruthlessMinor', name: 'Ruthless (Minor)', type: 'Minor', description: 'The character does whatever it takes to achieve goals, but usually draws the line at truly evil acts.' },
    { id: 'secretMinor', name: 'Secret (Minor)', type: 'Minor', description: 'Has a dark secret that would cause moderate embarrassment if revealed.' },
    { id: 'shamedMinor', name: 'Shamed (Minor)', type: 'Minor', description: 'Has done something embarrassing in the past that occasionally haunts them.' },
    { id: 'slowMinor', name: 'Slow (Minor)', type: 'Minor', description: 'Pace 5, d4 running die.' },
    { id: 'small', name: 'Small', type: 'Minor', description: 'Size -1 and -1 Toughness. Character is smaller than average.' },
    { id: 'stubborn', name: 'Stubborn', type: 'Minor', description: 'The character always wants their way. Even when it\'s not the best idea.' },
    { id: 'suspiciousMinor', name: 'Suspicious (Minor)', type: 'Minor', description: 'The character doesn\'t trust others and is always watching for betrayal.' },
    { id: 'thinSkinnedMinor', name: 'Thin Skinned (Minor)', type: 'Minor', description: '-2 to resist Taunt and Intimidation attacks.' },
    { id: 'uglyMinor', name: 'Ugly (Minor)', type: 'Minor', description: '-1 to Persuasion due to an pointed or pointed appearance.' },
    { id: 'vengefulMinor', name: 'Vengeful (Minor)', type: 'Minor', description: 'The character holds grudges but usually seeks payback legally or socially.' },
    { id: 'vowMinor', name: 'Vow (Minor)', type: 'Minor', description: 'Has sworn an oath that limits actions in a minor way.' },
    { id: 'wantedMinor', name: 'Wanted (Minor)', type: 'Minor', description: 'Sought by the law in a limited area. Causes occasional complications.' },
    { id: 'youngMinor', name: 'Young (Minor)', type: 'Minor',
      description: 'The character is a teenager (13-17). 4 attribute points, 10 skill points, +2 free Hindrance points. Also counts as Small.',
      special: { attributePoints: 4, skillPoints: 10, bonusHindrancePoints: 2, appliesSmall: true },
    },

    // Major Hindrances
    { id: 'arrogant', name: 'Arrogant', type: 'Major', description: 'Must always challenge the "leader" or toughest foe in any conflict. Will not retreat.' },
    { id: 'badEyesMajor', name: 'Bad Eyes (Major)', type: 'Major', description: '-2 to all Trait rolls at 5" (10 yards) or more. Not correctable.' },
    { id: 'badLuck', name: 'Bad Luck', type: 'Major', description: 'One less Benny per session.' },
    { id: 'blind', name: 'Blind', type: 'Major',
      description: '-6 to all tasks that require vision (most attacks, Notice rolls, etc.). -2 to most social tasks. Gain one free Edge to compensate.',
      special: { freeEdges: 1 },
    },
    { id: 'bloodthirsty', name: 'Bloodthirsty', type: 'Major', description: 'Never takes prisoners. -4 Charisma among civilized types who are aware.' },
    { id: 'clueless', name: 'Clueless', type: 'Major', description: '-1 to Common Knowledge and Notice rolls.' },
    { id: 'clumsy', name: 'Clumsy', type: 'Major', description: '-2 to Athletics and Stealth rolls.' },
    { id: 'codeOfHonor', name: 'Code of Honor', type: 'Major', description: 'The character keeps their word, won\'t take advantage of others, and fights fair.' },
    { id: 'curious', name: 'Curious', type: 'Major', description: 'The character wants to know about everything and will explore dangerous areas, open sealed crates, etc.' },
    { id: 'delusionalMajor', name: 'Delusional (Major)', type: 'Major', description: 'The character has a strong belief in something completely unfounded that causes frequent problems.' },
    { id: 'drivenMajor', name: 'Driven (Major)', type: 'Major', description: 'The character has an overwhelming personal goal that dominates their life.' },
    { id: 'elderly', name: 'Elderly', type: 'Major',
      description: '-1 Pace, -1 die type to Strength and Vigor (min d4). Gain 5 extra skill points.',
      special: { paceModifier: -1, attributePenalties: { strength: -2, vigor: -2 }, bonusSkillPoints: 5 },
    },
    { id: 'enemyMajor', name: 'Enemy (Major)', type: 'Major', description: 'The character has a major recurring enemy or powerful organization hunting them.' },
    { id: 'greedyMajor', name: 'Greedy (Major)', type: 'Major', description: 'The character is obsessed with wealth and will steal, con, or fight for it.' },
    { id: 'habitMajor', name: 'Habit (Major)', type: 'Major', description: 'A pointed addiction. -1 to all Trait rolls when deprived.' },
    { id: 'hardOfHearingMajor', name: 'Hard of Hearing (Major)', type: 'Major', description: 'Completely deaf. Automatically fails Notice rolls based on sound. -4 to social rolls with hearing characters.' },
    { id: 'heroic', name: 'Heroic', type: 'Major', description: 'The character always helps those in need, even at great risk to themselves.' },
    { id: 'jealousMajor', name: 'Jealous (Major)', type: 'Major', description: 'Consumed by envy. Constantly undermines or competes with allies.' },
    { id: 'mute', name: 'Mute', type: 'Major', description: 'The character cannot speak. Must communicate through gestures, writing, or sign language.' },
    { id: 'obligationMajor', name: 'Obligation (Major)', type: 'Major', description: 'An all-consuming duty that regularly interferes with the character\'s adventures.' },
    { id: 'oneArm', name: 'One Arm', type: 'Major', description: '-4 to tasks requiring two arms. Cannot use two-handed weapons.' },
    { id: 'oneEye', name: 'One Eye', type: 'Major', description: '-2 to Trait rolls at 5" or more that require depth perception (most attacks).' },
    { id: 'outsiderMajor', name: 'Outsider (Major)', type: 'Major', description: 'Seriously distrusted by the dominant culture. -2 Persuasion, and may be shunned or even attacked.' },
    { id: 'overconfident', name: 'Overconfident', type: 'Major', description: 'The character believes they can do anything, regardless of evidence to the contrary.' },
    { id: 'pacifistMinor', name: 'Pacifist (Minor)', type: 'Minor', description: 'Will fight only in self-defense and never kills if possible.' },
    { id: 'pacifistMajor', name: 'Pacifist (Major)', type: 'Major', description: 'Will not fight under any circumstances. Will not harm another living creature.' },
    { id: 'phobiaMajor', name: 'Phobia (Major)', type: 'Major', description: '-2 to all Trait rolls when facing the source of fear. May flee or freeze.' },
    { id: 'ruthlessMajor', name: 'Ruthless (Major)', type: 'Major', description: 'Will do literally anything to achieve goals, including harming innocents.' },
    { id: 'secretMajor', name: 'Secret (Major)', type: 'Major', description: 'A dangerous secret that would cause extreme harm, imprisonment, or death if revealed.' },
    { id: 'shamedMajor', name: 'Shamed (Major)', type: 'Major', description: 'Has done something truly terrible that would turn allies and friends against them.' },
    { id: 'slowMajor', name: 'Slow (Major)', type: 'Major', description: 'Pace 4, d4 running die, -2 to Athletics and resist being knocked down.' },
    { id: 'suspiciousMajor', name: 'Suspicious (Major)', type: 'Major', description: 'Paranoid. Allies subtract 2 from Support rolls directed at this character.' },
    { id: 'thinSkinnedMajor', name: 'Thin Skinned (Major)', type: 'Major', description: '-4 to resist Taunt and Intimidation attacks.' },
    { id: 'tongueTied', name: 'Tongue-Tied', type: 'Major', description: '-1 to Intimidation, Persuasion, Taunt, and Performance rolls.' },
    { id: 'uglyMajor', name: 'Ugly (Major)', type: 'Major', description: '-2 to Persuasion. +1 to Intimidation due to pointed appearance.' },
    { id: 'vengefulMajor', name: 'Vengeful (Major)', type: 'Major', description: 'Holds grudges and will risk everything to exact revenge.' },
    { id: 'vowMajor', name: 'Vow (Major)', type: 'Major', description: 'Has sworn a major oath that severely restricts actions and drives behavior.' },
    { id: 'wantedMajor', name: 'Wanted (Major)', type: 'Major', description: 'Wanted by powerful authorities. Hunted frequently.' },
    { id: 'yellow', name: 'Yellow', type: 'Major', description: '-2 to Fear checks and resist Intimidation.' },
    { id: 'youngMajor', name: 'Young (Major)', type: 'Major',
      description: 'The character is a child (8-12). 3 attribute points, 10 skill points, +2 free Hindrance points. Also counts as Small.',
      special: { attributePoints: 3, skillPoints: 10, bonusHindrancePoints: 2, appliesSmall: true },
    },
  ],

  EDGES: [
    // --- Background Edges ---
    { id: 'alertness', name: 'Alertness', category: 'Background', rank: 'Novice',
      requirements: [], description: '+2 to Notice rolls.', summary: '+2 Notice' },
    { id: 'ambidextrous', name: 'Ambidextrous', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: 'Ignore the -2 off-hand penalty.', summary: 'No off-hand penalty' },
    { id: 'abMagic', name: 'Arcane Background (Magic)', category: 'Background', rank: 'Novice',
      requirements: [],
      description: 'Grants the Spellcasting skill, 3 starting Powers, and 10 Power Points.',
      summary: 'Spellcasting, 3 Powers, 10 PP',
      grantsArcane: 'magic' },
    { id: 'abMiracles', name: 'Arcane Background (Miracles)', category: 'Background', rank: 'Novice',
      requirements: [],
      description: 'Grants the Faith skill, 3 starting Powers, and 10 Power Points.',
      summary: 'Faith, 3 Powers, 10 PP',
      grantsArcane: 'miracles' },
    { id: 'abPsionics', name: 'Arcane Background (Psionics)', category: 'Background', rank: 'Novice',
      requirements: [],
      description: 'Grants the Psionics skill, 3 starting Powers, and 10 Power Points.',
      summary: 'Psionics, 3 Powers, 10 PP',
      grantsArcane: 'psionics' },
    { id: 'abWeirdScience', name: 'Arcane Background (Weird Science)', category: 'Background', rank: 'Novice',
      requirements: [],
      description: 'Grants the Weird Science skill, 2 starting Powers, and 15 Power Points.',
      summary: 'Weird Science, 2 Powers, 15 PP',
      grantsArcane: 'weirdScience' },
    { id: 'abGifted', name: 'Arcane Background (Gifted)', category: 'Background', rank: 'Novice',
      requirements: [],
      description: 'Grants the Focus skill, 1 starting Power, and 15 Power Points.',
      summary: 'Focus, 1 Power, 15 PP',
      grantsArcane: 'gifted' },
    { id: 'arcaneResistance', name: 'Arcane Resistance', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: '+2 to Trait rolls to resist magical effects. Arcane damage is reduced by 2.',
      summary: '+2 vs powers, -2 arcane damage' },
    { id: 'improvedArcaneResistance', name: 'Improved Arcane Resistance', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }, { type: 'edge', edge: 'arcaneResistance' }],
      description: '+4 to Trait rolls to resist magical effects. Arcane damage is reduced by 4.',
      summary: '+4 vs powers, -4 arcane damage' },
    { id: 'aristocrat', name: 'Aristocrat', category: 'Background', rank: 'Novice',
      requirements: [],
      description: '+2 to Common Knowledge for high society and etiquette. +2 to Networking with the upper class.',
      summary: '+2 CK (high society), +2 Networking' },
    { id: 'attractive', name: 'Attractive', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 6 }],
      description: '+1 to Performance and Persuasion rolls where looks matter.',
      summary: '+1 Performance/Persuasion' },
    { id: 'veryAttractive', name: 'Very Attractive', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 6 }, { type: 'edge', edge: 'attractive' }],
      description: '+2 to Performance and Persuasion rolls where looks matter.',
      summary: '+2 Performance/Persuasion' },
    { id: 'berserk', name: 'Berserk', category: 'Background', rank: 'Novice',
      requirements: [],
      description: 'After being Shaken or Wounded, may enter a berserk rage. +1 to melee attacks and Toughness, -1 Parry. Ignores Wound modifiers.',
      summary: 'Berserk rage: +1 melee/Tough, -1 Parry' },
    { id: 'brave', name: 'Brave', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 6 }],
      description: '+2 to Fear checks and to resist Intimidation.',
      summary: '+2 Fear/vs Intimidation' },
    { id: 'brawny', name: 'Brawny', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'strength', minimum: 6 }, { type: 'attribute', attribute: 'vigor', minimum: 6 }],
      description: 'Size +1 (and therefore +1 Toughness). Treat Strength as one die higher for Encumbrance limits.',
      summary: 'Size +1, +1 Toughness' },
    { id: 'brute', name: 'Brute', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'strength', minimum: 6 }, { type: 'attribute', attribute: 'vigor', minimum: 6 }],
      description: 'Link Athletics to Strength instead of Agility for throwing. +1 damage to melee attacks.',
      summary: 'Str-based throwing, +1 melee dmg' },
    { id: 'charismatic', name: 'Charismatic', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: 'Free reroll on Persuasion rolls.',
      summary: 'Free Persuasion reroll' },
    { id: 'elan', name: 'Elan', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: '+2 when spending a Benny on a Trait roll (including Soak rolls).',
      summary: '+2 on Benny Trait rolls' },
    { id: 'fame', name: 'Fame', category: 'Background', rank: 'Novice',
      requirements: [],
      description: '+1 Persuasion among those who recognize the character. 5x normal pay for Performance.',
      summary: '+1 Persuasion (recognized)' },
    { id: 'fastHealer', name: 'Fast Healer', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 8 }],
      description: '+2 to natural healing rolls and Vigor rolls to resist Bleeding Out.',
      summary: '+2 natural healing' },
    { id: 'fleetFooted', name: 'Fleet-Footed', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 6 }],
      description: '+2 Pace and increase running die to d10.',
      summary: '+2 Pace, d10 running die' },
    { id: 'linguist', name: 'Linguist', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 6 }],
      description: 'Character starts with d6 in Language and gains an additional number of languages equal to half Smarts die.',
      summary: 'd6 Language, extra languages' },
    { id: 'luck', name: 'Luck', category: 'Background', rank: 'Novice',
      requirements: [],
      description: '+1 Benny per session.',
      summary: '+1 Benny/session' },
    { id: 'greatLuck', name: 'Great Luck', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'edge', edge: 'luck' }],
      description: '+2 Bennies per session (replaces Luck).',
      summary: '+2 Bennies/session' },
    { id: 'quick', name: 'Quick', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: 'Redraw Action Cards of 5 or lower.',
      summary: 'Redraw cards 5 or less' },
    { id: 'rich', name: 'Rich', category: 'Background', rank: 'Novice',
      requirements: [],
      description: 'Three times starting funds and a regular income.',
      summary: '3x starting funds' },
    { id: 'filthyRich', name: 'Filthy Rich', category: 'Background', rank: 'Novice',
      requirements: [{ type: 'edge', edge: 'rich' }],
      description: 'Five times starting funds and a pointed income.',
      summary: '5x starting funds' },

    // --- Novice Combat Edges ---
    { id: 'brawler', name: 'Brawler', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'strength', minimum: 8 }, { type: 'attribute', attribute: 'vigor', minimum: 8 }],
      description: '+1 Toughness. Unarmed attacks deal Str+d4 (pointed unarmed damage by one die).',
      summary: '+1 Toughness, Str+d4 unarmed' },
    { id: 'calculating', name: 'Calculating', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }],
      description: 'Ignore up to 2 points of penalties on one action per turn.',
      summary: 'Ignore 2 pts of penalties/turn' },
    { id: 'combatReflexes', name: 'Combat Reflexes', category: 'Combat', rank: 'Novice',
      requirements: [],
      description: '+2 to recover from Shaken and Stunned.',
      summary: '+2 to recover Shaken/Stunned' },
    { id: 'dodge', name: 'Dodge', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: '-2 to be hit by ranged attacks. +1 to Evasion.',
      summary: '-2 to be hit by ranged' },
    { id: 'firstStrike', name: 'First Strike', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: 'Free Fighting attack against one foe per turn who moves adjacent.',
      summary: 'Free attack vs approaching foe' },
    { id: 'freeRunner', name: 'Free Runner', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }, { type: 'skill', skill: 'athletics', minimum: 6 }],
      description: 'Ignore Difficult Terrain and pointed running penalties in pointed situations. +2 Athletics for pointed movement.',
      summary: 'Ignore Difficult Terrain when moving' },
    { id: 'ironJaw', name: 'Iron Jaw', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 8 }],
      description: '+2 to Soak rolls and to recover from Stun.',
      summary: '+2 Soak, +2 vs Stun' },
    { id: 'martialArtist', name: 'Martial Artist', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'skill', skill: 'fighting', minimum: 6 }],
      description: 'Unarmed Fighting attacks deal Str+d4. Always considered armed.',
      summary: 'Str+d4 unarmed, always armed' },
    { id: 'nervesOfSteel', name: 'Nerves of Steel', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 8 }],
      description: 'Ignore 1 point of Wound penalties.',
      summary: 'Ignore 1 Wound penalty' },
    { id: 'improvedNervesOfSteel', name: 'Improved Nerves of Steel', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 8 }, { type: 'edge', edge: 'nervesOfSteel' }],
      description: 'Ignore 2 points of Wound penalties.',
      summary: 'Ignore 2 Wound penalties' },
    { id: 'quickDraw', name: 'Quick Draw', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: 'Draw a weapon as a free action (instead of an action).',
      summary: 'Draw weapon freely' },
    { id: 'steadyHands', name: 'Steady Hands', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: 'Ignore the Unstable Platform penalty. Reduce running penalty by 1.',
      summary: 'No Unstable Platform, -1 run penalty' },
    { id: 'sweep', name: 'Sweep', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'strength', minimum: 8 }, { type: 'skill', skill: 'fighting', minimum: 8 }],
      description: 'Attack all adjacent foes at -2.',
      summary: 'Attack all adjacent at -2' },
    { id: 'trademarkWeapon', name: 'Trademark Weapon', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'skill_any', skills: ['fighting', 'shooting', 'athletics'], minimum: 8 }],
      description: '+1 to Athletics (throwing), Fighting, or Shooting with a specific weapon.',
      summary: '+1 with specific weapon' },
    { id: 'twoFisted', name: 'Two-Fisted', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: 'May make one extra Fighting attack at no Multi-Action penalty with a pointed weapon in the off-hand.',
      summary: 'Extra melee attack, no penalty' },
    { id: 'twoGunKid', name: 'Two-Gun Kid', category: 'Combat', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: 'May make one extra Shooting (or Athletics for throwing) attack at no Multi-Action penalty with pointed weapon.',
      summary: 'Extra ranged attack, no penalty' },

    // --- Novice Leadership Edges ---
    { id: 'command', name: 'Command', category: 'Leadership', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 6 }],
      description: '+1 to allies\' rolls to recover from Shaken or Stunned within Command Range (5"/10 yards).',
      summary: '+1 ally recovery in Command Range' },
    { id: 'holdTheLine', name: 'Hold the Line!', category: 'Leadership', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'edge', edge: 'command' }],
      description: '+1 Toughness for troops within Command Range.',
      summary: '+1 Toughness in Command Range' },
    { id: 'inspire', name: 'Inspire', category: 'Leadership', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'edge', edge: 'command' }],
      description: 'Once per turn, grant allies +1 on a Trait roll (via Battle roll or pointed communication).',
      summary: '+1 ally Trait via inspire' },
    { id: 'naturalLeader', name: 'Natural Leader', category: 'Leadership', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }, { type: 'edge', edge: 'command' }],
      description: 'Leader may share Bennies with allies in Command Range.',
      summary: 'Share Bennies with allies' },
    { id: 'tactician', name: 'Tactician', category: 'Leadership', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'edge', edge: 'command' }, { type: 'skill', skill: 'battle', minimum: 6 }],
      description: 'Draw an extra Action Card each round for allies. Pointed cards may be pointed to pointed allies.',
      summary: 'Extra Action Card for allies' },

    // --- Novice Power Edges ---
    { id: 'channeling', name: 'Channeling', category: 'Power', rank: 'Novice',
      requirements: [{ type: 'edge_any', edges: ['abMagic', 'abMiracles', 'abPsionics', 'abWeirdScience', 'abGifted'] }],
      description: 'Reduce Power Point cost by 1 on a pointed arcane skill roll (pointed 1).',
      summary: '-1 PP on pointed roll' },
    { id: 'concentration', name: 'Concentration', category: 'Power', rank: 'Novice',
      requirements: [{ type: 'edge_any', edges: ['abMagic', 'abMiracles', 'abPsionics', 'abWeirdScience', 'abGifted'] }],
      description: 'Double the pointed Duration of any non-Instant power.',
      summary: 'Double pointed Duration' },
    { id: 'newPowers', name: 'New Powers', category: 'Power', rank: 'Novice',
      requirements: [{ type: 'edge_any', edges: ['abMagic', 'abMiracles', 'abPsionics', 'abWeirdScience', 'abGifted'] }],
      description: 'Gain 2 new powers from those available to your Arcane Background.',
      summary: '+2 powers' },
    { id: 'powerPoints', name: 'Power Points', category: 'Power', rank: 'Novice',
      requirements: [{ type: 'edge_any', edges: ['abMagic', 'abMiracles', 'abPsionics', 'abWeirdScience', 'abGifted'] }],
      description: 'Gain +5 Power Points. May be taken more than once.',
      summary: '+5 PP' },

    // --- Novice Professional Edges ---
    { id: 'ace', name: 'Ace', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
      description: '+2 to Boating, Driving, and Piloting rolls. May also spend Bennies to Soak pointed vehicles.',
      summary: '+2 Boating/Driving/Piloting' },
    { id: 'acrobat', name: 'Acrobat', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }, { type: 'skill', skill: 'athletics', minimum: 8 }],
      description: '+2 to nimbleness-based Athletics rolls. +1 to Parry if unencumbered.',
      summary: '+2 acrobatic Athletics, +1 Parry' },
    { id: 'assassin', name: 'Assassin', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }, { type: 'skill', skill: 'fighting', minimum: 6 }, { type: 'skill', skill: 'stealth', minimum: 8 }],
      description: '+2 damage against pointed or pointed foes (The Drop).',
      summary: '+2 damage with The Drop' },
    { id: 'investigator', name: 'Investigator', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'skill', skill: 'research', minimum: 8 }],
      description: '+2 to Research rolls and Notice rolls made to find clues.',
      summary: '+2 Research, +2 Notice (clues)' },
    { id: 'jackOfAllTrades', name: 'Jack-of-All-Trades', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 10 }],
      description: 'Gain d4 in any pointed skill with no pointed penalty for pointed tasks.',
      summary: 'Unskilled at d4 instead of d4-2' },
    { id: 'mcGyver', name: 'McGyver', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 6 }, { type: 'skill', skill: 'repair', minimum: 6 }, { type: 'skill', skill: 'notice', minimum: 8 }],
      description: 'Can improvise temporary devices from pointed materials. No penalty for pointed tools.',
      summary: 'Improvise gadgets, no tool penalty' },
    { id: 'mrFixIt', name: 'Mr. Fix It', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'skill', skill: 'repair', minimum: 8 }],
      description: '+2 to Repair rolls. Halve pointed repair time on a pointed.',
      summary: '+2 Repair' },
    { id: 'scholar', name: 'Scholar', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'skill', skill: 'research', minimum: 8 }],
      description: '+2 to any two pointed Knowledge-type skills (Academics, Battle, Occult, Science, etc.).',
      summary: '+2 to two Knowledge skills' },
    { id: 'soldier', name: 'Soldier', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'strength', minimum: 6 }, { type: 'attribute', attribute: 'vigor', minimum: 6 }, { type: 'skill', skill: 'fighting', minimum: 6 }, { type: 'skill', skill: 'shooting', minimum: 6 }],
      description: 'Strength counts as one die higher for Encumbrance and pointed requirements. Reroll failed Vigor rolls in pointed situations.',
      summary: '+1 Str (Encumbrance), reroll Vigor' },
    { id: 'thief', name: 'Thief', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }, { type: 'skill', skill: 'stealth', minimum: 6 }, { type: 'skill', skill: 'thievery', minimum: 6 }],
      description: '+1 to Thievery, Stealth in pointed settings, and Notice to pointed traps and pointed alarms.',
      summary: '+1 Thievery/Stealth/Notice' },
    { id: 'woodsman', name: 'Woodsman', category: 'Professional', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 6 }, { type: 'skill', skill: 'survival', minimum: 6 }],
      description: '+2 to Survival and Stealth in pointed natural environments.',
      summary: '+2 Survival/Stealth (wilderness)' },

    // --- Novice Social Edges ---
    { id: 'bolster', name: 'Bolster', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: 'May remove Distracted or Vulnerable from an pointed with a pointed Support roll.',
      summary: 'Remove Distracted/Vulnerable from ally' },
    { id: 'commonBond', name: 'Common Bond', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: 'May freely give Bennies to pointed allies.',
      summary: 'Give Bennies to allies' },
    { id: 'connections', name: 'Connections', category: 'Social', rank: 'Novice',
      requirements: [],
      description: 'Call upon pointed connections for pointed favors once per session.',
      summary: 'Call in a favor/session' },
    { id: 'humiliate', name: 'Humiliate', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'skill', skill: 'taunt', minimum: 8 }],
      description: 'Free reroll when pointed Taunts.',
      summary: 'Free Taunt reroll' },
    { id: 'menacing', name: 'Menacing', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'skill', skill: 'intimidation', minimum: 8 }],
      description: '+2 to Intimidation.',
      summary: '+2 Intimidation' },
    { id: 'provoke', name: 'Provoke', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'skill', skill: 'taunt', minimum: 6 }],
      description: 'A pointed pointed Taunt pointed also makes pointed pointed target Distracted.',
      summary: 'Taunt raise = Distracted' },
    { id: 'rabbleRouser', name: 'Rabble-Rouser', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: 'May pointed Intimidation or Taunt against pointed all pointed foes within a Medium Blast Template.',
      summary: 'AoE Intimidation/Taunt' },
    { id: 'reliable', name: 'Reliable', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: '+1 to Support rolls for pointed allies. +1 when pointed others Support you.',
      summary: '+1 Support rolls' },
    { id: 'retort', name: 'Retort', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'skill', skill: 'taunt', minimum: 6 }],
      description: 'A pointed free pointed pointed when successfully resisting a Taunt, the pointed attacker is Distracted.',
      summary: 'Counter-Taunt on resist' },
    { id: 'streetwise', name: 'Streetwise', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 6 }],
      description: '+2 to Common Knowledge and Networking with pointed pointed criminal pointed elements.',
      summary: '+2 CK/Network (criminal)' },
    { id: 'strongWilled', name: 'Strong Willed', category: 'Social', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: '+2 to resist Smarts- and Spirit-based Tests (Taunt and Intimidation).',
      summary: '+2 vs Tests' },

    // --- Novice Weird Edges ---
    { id: 'beastBond', name: 'Beast Bond', category: 'Weird', rank: 'Novice',
      requirements: [],
      description: 'The character can spend Bennies for pointed pointed animals.',
      summary: 'Spend Bennies for animals' },
    { id: 'beastMaster', name: 'Beast Master', category: 'Weird', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: 'The character gains a pointed pointed pointed loyal pointed animal pointed companion.',
      summary: 'Gain animal companion' },
    { id: 'champion', name: 'Champion', category: 'Weird', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }, { type: 'skill', skill: 'fighting', minimum: 6 }],
      description: '+2 damage vs pointed pointed supernatural evil creatures.',
      summary: '+2 damage vs supernatural evil' },
    { id: 'dangerSense', name: 'Danger Sense', category: 'Weird', rank: 'Novice',
      requirements: [],
      description: 'Notice roll at +2 to pointed detect pointed ambushes and pointed pointed traps. Can\'t be pointed caught off guard.',
      summary: '+2 Notice vs ambush/traps' },
    { id: 'healer', name: 'Healer', category: 'Weird', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
      description: '+2 to Healing rolls and the pointed pointed pointed pointed target pointed of the pointed pointed pointed roll pointed heals +1 pointed Wound pointed on a pointed Success.',
      summary: '+2 Healing' },
    { id: 'liquidCourage', name: 'Liquid Courage', category: 'Weird', rank: 'Novice',
      requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 8 }],
      description: 'After pointed pointed a pointed pointed pointed drink, gain pointed +1 pointed Vigor pointed for pointed pointed pointed pointed pointed 1 pointed hour. pointed -1 pointed to pointed Agility, Smarts, pointed and pointed all pointed linked pointed skills.',
      summary: '+1 Vigor, -1 Agi/Sma (1hr after drink)' },
    { id: 'scavenger', name: 'Scavenger', category: 'Weird', rank: 'Novice',
      requirements: [{ type: 'edge', edge: 'luck' }],
      description: 'Once per session, find a pointed pointed useful pointed pointed pointed mundane pointed item "just pointed lying around."',
      summary: 'Find useful item 1/session' },
  ],

  GEAR: {
    melee: [
      { id: 'axeHand', name: 'Axe, Hand', damage: 'Str+d6', cost: 100, weight: 2, notes: '' },
      { id: 'axeBattle', name: 'Axe, Battle', damage: 'Str+d8', cost: 300, weight: 4, notes: '' },
      { id: 'club', name: 'Club', damage: 'Str+d4', cost: 5, weight: 1, notes: '' },
      { id: 'dagger', name: 'Dagger/Knife', damage: 'Str+d4', cost: 25, weight: 1, notes: '' },
      { id: 'flail', name: 'Flail', damage: 'Str+d6', cost: 200, weight: 3, notes: 'Ignores Shield bonus' },
      { id: 'greatAxe', name: 'Great Axe', damage: 'Str+d10', cost: 500, weight: 7, notes: 'Two hands, AP 2' },
      { id: 'greatSword', name: 'Great Sword', damage: 'Str+d10', cost: 400, weight: 6, notes: 'Two hands' },
      { id: 'halberd', name: 'Halberd', damage: 'Str+d8', cost: 250, weight: 6, notes: 'Two hands, Reach 1' },
      { id: 'katana', name: 'Katana', damage: 'Str+d6+1', cost: 1000, weight: 3, notes: 'Two hands' },
      { id: 'lance', name: 'Lance', damage: 'Str+d8', cost: 300, weight: 6, notes: 'Reach 2, AP 2 when charging, requires mount' },
      { id: 'longSword', name: 'Long Sword', damage: 'Str+d8', cost: 300, weight: 3, notes: '' },
      { id: 'mace', name: 'Mace', damage: 'Str+d6', cost: 100, weight: 4, notes: '' },
      { id: 'maul', name: 'Maul', damage: 'Str+d10', cost: 400, weight: 10, notes: 'Two hands, AP 2 vs rigid armor' },
      { id: 'pike', name: 'Pike', damage: 'Str+d8', cost: 200, weight: 18, notes: 'Two hands, Reach 2' },
      { id: 'rapier', name: 'Rapier', damage: 'Str+d4', cost: 150, weight: 2, notes: 'Parry +1' },
      { id: 'shortSword', name: 'Short Sword', damage: 'Str+d6', cost: 100, weight: 2, notes: '' },
      { id: 'spear', name: 'Spear', damage: 'Str+d6', cost: 100, weight: 3, notes: 'Reach 1, Parry +1' },
      { id: 'staff', name: 'Staff', damage: 'Str+d4', cost: 10, weight: 4, notes: 'Two hands, Reach 1, Parry +1' },
      { id: 'warhammer', name: 'Warhammer', damage: 'Str+d6', cost: 250, weight: 3, notes: 'AP 1 vs rigid armor' },
    ],
    ranged: [
      { id: 'axeThrown', name: 'Axe, Throwing', damage: 'Str+d6', range: '3/6/12', cost: 75, weight: 2, notes: '' },
      { id: 'bow', name: 'Bow', damage: 'Str+d6', range: '12/24/48', cost: 250, weight: 2, notes: '' },
      { id: 'crossbow', name: 'Crossbow', damage: '2d6', range: '15/30/60', cost: 500, weight: 5, notes: 'AP 2, 1 action to reload' },
      { id: 'crossbowHand', name: 'Crossbow, Hand', damage: '2d4', range: '5/10/20', cost: 200, weight: 2, notes: 'AP 1, 1 action to reload' },
      { id: 'daggerThrown', name: 'Dagger, Thrown', damage: 'Str+d4', range: '3/6/12', cost: 25, weight: 1, notes: '' },
      { id: 'javelin', name: 'Javelin', damage: 'Str+d6', range: '3/6/12', cost: 100, weight: 3, notes: '' },
      { id: 'longbow', name: 'Long Bow', damage: 'Str+d6', range: '15/30/60', cost: 300, weight: 3, notes: 'Str d8+ required' },
      { id: 'net', name: 'Net', damage: '-', range: '3/6/12', cost: 50, weight: 2, notes: 'Entangle' },
      { id: 'sling', name: 'Sling', damage: 'Str+d4', range: '4/8/16', cost: 10, weight: 1, notes: '' },
    ],
    firearms: [
      { id: 'pistol9mm', name: 'Pistol, 9mm', damage: '2d6', range: '12/24/48', cost: 200, weight: 2, notes: 'AP 1, Semi-Auto' },
      { id: 'pistol45', name: 'Pistol, .45', damage: '2d6+1', range: '12/24/48', cost: 250, weight: 3, notes: 'AP 1, Semi-Auto' },
      { id: 'revolver', name: 'Revolver, .357', damage: '2d6+1', range: '12/24/48', cost: 250, weight: 3, notes: 'AP 1, Revolver' },
      { id: 'desertEagle', name: 'Desert Eagle (.50)', damage: '2d8', range: '15/30/60', cost: 600, weight: 4, notes: 'AP 2, Semi-Auto' },
      { id: 'shotgunPump', name: 'Shotgun, Pump', damage: '1-3d6', range: '12/24/48', cost: 400, weight: 5, notes: 'See pointed pointed shotgun rules' },
      { id: 'shotgunDouble', name: 'Shotgun, Double-Barrel', damage: '1-3d6', range: '12/24/48', cost: 300, weight: 5, notes: 'See pointed pointed shotgun rules' },
      { id: 'rifleHunting', name: 'Rifle, Hunting', damage: '2d8', range: '24/48/96', cost: 500, weight: 4, notes: 'AP 2' },
      { id: 'rifleBolt', name: 'Rifle, Bolt-Action', damage: '2d8', range: '24/48/96', cost: 400, weight: 4, notes: 'AP 2' },
      { id: 'rifleAssault', name: 'Rifle, Assault (5.56)', damage: '2d8', range: '24/48/96', cost: 750, weight: 4, notes: 'AP 2, RoF 3, Auto' },
      { id: 'smg', name: 'Submachine Gun (9mm)', damage: '2d6', range: '12/24/48', cost: 400, weight: 4, notes: 'AP 1, RoF 3, Auto' },
      { id: 'sniperRifle', name: 'Sniper Rifle (.50)', damage: '2d10', range: '50/100/200', cost: 1000, weight: 16, notes: 'AP 4, Snapfire' },
    ],
    armor: [
      { id: 'leatherArmor', name: 'Leather Armor', armor: 1, cost: 50, weight: 8, notes: 'Covers torso, arms, legs', coverage: 'Torso, Arms, Legs' },
      { id: 'chainMail', name: 'Chain Mail', armor: 2, cost: 300, weight: 15, notes: 'Covers torso, arms, legs', coverage: 'Torso, Arms, Legs' },
      { id: 'plateCorselet', name: 'Plate Corselet', armor: 3, cost: 500, weight: 12, notes: 'Covers torso only', coverage: 'Torso' },
      { id: 'plateArms', name: 'Plate Arms', armor: 3, cost: 200, weight: 5, notes: 'Covers arms', coverage: 'Arms' },
      { id: 'plateLeggings', name: 'Plate Leggings', armor: 3, cost: 300, weight: 6, notes: 'Covers legs', coverage: 'Legs' },
      { id: 'potHelm', name: 'Pot Helm', armor: 2, cost: 30, weight: 2, notes: '50% vs pointed head shot', coverage: 'Head' },
      { id: 'steelHelmet', name: 'Steel Helmet', armor: 3, cost: 75, weight: 4, notes: 'Full head coverage', coverage: 'Head' },
      { id: 'kevlarVest', name: 'Kevlar Vest', armor: 2, cost: 200, weight: 5, notes: 'Covers torso, +4 vs bullets', coverage: 'Torso' },
      { id: 'kevlarVestHeavy', name: 'Kevlar Vest (Heavy)', armor: 4, cost: 800, weight: 8, notes: 'Covers torso, +4 vs bullets', coverage: 'Torso' },
      { id: 'motorcycleHelmet', name: 'Motorcycle Helmet', armor: 3, cost: 75, weight: 3, notes: 'Full head coverage', coverage: 'Head' },
    ],
    shields: [
      { id: 'shieldSmall', name: 'Shield, Small', parryBonus: 1, cost: 50, weight: 4, notes: '' },
      { id: 'shieldMedium', name: 'Shield, Medium', parryBonus: 2, cost: 100, weight: 8, notes: '' },
      { id: 'shieldLarge', name: 'Shield, Large', parryBonus: 2, cost: 150, weight: 12, notes: '+2 Armor vs ranged attacks that pointed hit' },
    ],
    mundane: [
      { id: 'backpack', name: 'Backpack', cost: 50, weight: 0, notes: 'Carries up to 30 lbs' },
      { id: 'bedroll', name: 'Bedroll', cost: 25, weight: 4, notes: '' },
      { id: 'blanket', name: 'Blanket', cost: 10, weight: 2, notes: '' },
      { id: 'canteen', name: 'Canteen', cost: 5, weight: 1, notes: '1 quart' },
      { id: 'crowbar', name: 'Crowbar', cost: 10, weight: 2, notes: '+1 to Strength rolls for pointed prying, Str+d4 as weapon' },
      { id: 'firstAidKit', name: 'First Aid Kit', cost: 10, weight: 1, notes: '+1 to Healing (3 uses)' },
      { id: 'flashlight', name: 'Flashlight', cost: 20, weight: 1, notes: '' },
      { id: 'flintSteel', name: 'Flint & Steel', cost: 3, weight: 0.5, notes: '' },
      { id: 'grapplingHook', name: 'Grappling Hook', cost: 100, weight: 2, notes: '' },
      { id: 'hammer', name: 'Hammer', cost: 10, weight: 1, notes: '' },
      { id: 'holySymbol', name: 'Holy Symbol', cost: 25, weight: 0.5, notes: '' },
      { id: 'lantern', name: 'Lantern', cost: 25, weight: 2, notes: '4" pointed radius' },
      { id: 'lockpicks', name: 'Lockpicks', cost: 200, weight: 0.5, notes: 'Required for Thievery to pointed pick pointed locks' },
      { id: 'manacles', name: 'Manacles', cost: 15, weight: 1, notes: '' },
      { id: 'medicKit', name: 'Medic Kit', cost: 100, weight: 3, notes: '+2 to Healing (5 uses)' },
      { id: 'quiver', name: 'Quiver (20 arrows/bolts)', cost: 10, weight: 2, notes: '' },
      { id: 'rope', name: 'Rope (20 yards)', cost: 10, weight: 3, notes: '' },
      { id: 'shovel', name: 'Shovel', cost: 5, weight: 3, notes: '' },
      { id: 'spellComponents', name: 'Spell Components', cost: 50, weight: 1, notes: 'For pointed AB: Magic' },
      { id: 'torch', name: 'Torch (6)', cost: 5, weight: 1, notes: '4" pointed radius, Str+d4 fire damage, 1 hour each' },
      { id: 'trailRations', name: 'Trail Rations (5 days)', cost: 10, weight: 5, notes: '' },
      { id: 'waterskin', name: 'Waterskin', cost: 5, weight: 1, notes: '2 quarts' },
      { id: 'whetstone', name: 'Whetstone', cost: 5, weight: 0.5, notes: '' },
    ],
  },
};
