// ============================================================
// SETTING-SPECIFIC DATA
// Deadlands (Weird West), Rifts, Pirates
// ============================================================

const SETTINGS = {
  deadlands: {
    id: 'deadlands',
    name: 'Deadlands',
    subtitle: 'The Weird West',
    description: 'The year is 1884, but the history is not our own. The dead walk among the living, ghost rock fuels mad science, and the Reckoners shape a world of fear. Gunslingers, hucksters, and the blessed fight back the darkness across the Weird West.',
    color: '#c45a3c',
    icon: '\u2606',
    banner: 'banner-deadlands.jpg',
    startingFunds: 250,

    tips: {
      setting: 'Deadlands is set in an alternate 1884 American frontier where the supernatural is real. Classic archetypes include Gunslingers, Hucksters (card-slinging sorcerers), Blessed (faith healers), Mad Scientists (ghost rock inventors), Shamans (nature spirit channelers), Chi Masters (martial artists), Agents (supernatural investigators), and Texas Rangers.',
      concept: 'Think about your character\'s role in the Weird West. Are you a fast-drawing gunslinger? A huckster who deals with demons for power? A blessed preacher fighting evil? A mad scientist building ghost rock gadgets? A shaman communing with nature spirits? Your concept will guide your Edge and skill choices.',
      race: 'In Deadlands, all characters are Human. Diversity comes from cultural background: African-American, Chinese, European, Mexican, or Native American. These are narrative choices \u2014 pick what fits your story. All humans get one free Novice Edge.',
      attributes: 'Your Arcane Background determines key attributes: Hucksters need Smarts (for Spellcasting). Blessed and Shamans need Spirit (for Faith). Chi Masters need Spirit and Agility (for Focus). Mad Scientists need Smarts (for Weird Science). Gunslingers want Agility for Shooting. Everyone benefits from Vigor for survivability.',
      skills: 'Key Deadlands skills: Shooting and Fighting for combat. Gambling is essential for Hucksters. Occult helps identify supernatural threats. Riding is vital on the frontier. Survival keeps you alive in the wilds. Healing saves lives when the doc is far away. Faith, Spellcasting, Weird Science, or Focus are needed for arcane characters.',
      hindrances: 'Deadlands hindrances reflect the dangers of the Weird West. Old Ways Oath is mandatory (and free) for Shamans. Ailin\' represents frontier diseases. Cursed brings supernatural bad luck. Consider hindrances that tie into your backstory \u2014 extra hindrance points can buy you an additional Edge or attribute raise.',
      edges: 'Arcane Backgrounds are the most impactful choice here. Hucksters deal with the devil for hexes. The Blessed channel divine power through faith. Shamans commune with nature spirits (and must take Old Ways Oath). Mad Scientists build ghost rock-powered infernal devices. Chi Masters channel inner energy through martial arts. You can also take profession edges like Agent or Territorial Ranger.',
      gear: 'Starting funds are $250 in the Weird West. A Colt Peacemaker is the classic sidearm. Winchester rifles are reliable. Grab a horse if you plan to travel. Ghost rock is expensive but fuels mad science. Silver bullets and holy water are essential against the supernatural. Don\'t forget basics: bedroll, trail rations, and a good knife.',
      summary: 'Review your character carefully. In Deadlands, balanced characters survive longest. Make sure you have at least one combat skill (Shooting or Fighting), a way to get around (Riding), and something that makes you unique. The Weird West is dangerous \u2014 be ready for anything.',
    },

    RACES: [
      {
        id: 'dl_human', name: 'Human',
        description: 'All folk of the Weird West are human \u2014 be they gunslingers, preachers, hucksters, mad scientists, or shamans. What sets you apart isn\'t your blood, but your grit, your choices, and whether you can keep your nerve when the dead start walking.',
        abilities: [
          { type: 'free_edge', count: 1, label: 'Adaptable', description: 'Humans begin with one free Novice Edge of their choice.' },
        ],
      },
    ],

    EDGES: [
      // --- Arcane Backgrounds ---
      { id: 'dl_abBlessed', name: 'Arcane Background: Blessed', category: 'Arcane Background', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
        description: 'You channel divine power through unwavering faith. Arcane Skill: Faith (Spirit). Starting Powers: 3, Power Points: 15. You must follow a strict moral code \u2014 sins impose penalties or disable your powers entirely. Available powers include Healing, Smite, Deflection, and more.',
        summary: 'Faith-based divine powers (15 PP, 3 powers)' },
      { id: 'dl_abHuckster', name: 'Arcane Background: Huckster', category: 'Arcane Background', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'gambling', minimum: 6 }],
        description: 'You deal with the devil \u2014 literally. Hucksters draw manitous into a mental poker game to fuel their hexes. Arcane Skill: Spellcasting (Smarts). Starting Powers: 3, Power Points: 10. Special: Spend a Benny to "Deal with the Devil" \u2014 draw cards and build a poker hand for bonus effects or to cast spells you don\'t even know. Jokers cause backfire!',
        summary: 'Deal with the Devil for hexes (10 PP, 3 powers)' },
      { id: 'dl_abShaman', name: 'Arcane Background: Shaman', category: 'Arcane Background', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
        description: 'You channel the power of nature spirits through ancient rituals. Arcane Skill: Faith (Spirit). Starting Powers: 2, Power Points: 15. You automatically take Old Ways Oath (Major) for free. Chanting is required \u2014 silence imposes -2. Cannot use mass-produced items or infernal devices without suffering Fatigue.',
        summary: 'Nature spirit rituals (15 PP, 2 powers, Old Ways Oath)' },
      { id: 'dl_abMadScientist', name: 'Arcane Background: Mad Scientist', category: 'Arcane Background', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'skill', skill: 'science', minimum: 6 }],
        description: 'You build ghost rock-powered Infernal Devices that replicate supernatural effects. Arcane Skill: Weird Science (Smarts). Starting Powers: 1, Power Points: 20. Warning: Rolling a 1 on the trait die causes malfunctions! Results range from minor (quick Repair roll) to catastrophic (3d6 explosion). Can also create shareable elixirs.',
        summary: 'Ghost rock gadgets (20 PP, 1 power, malfunctions)' },
      { id: 'dl_abChiMaster', name: 'Arcane Background: Chi Master', category: 'Arcane Background', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'agility', minimum: 6 }, { type: 'attribute', attribute: 'spirit', minimum: 8 }],
        description: 'You channel your inner chi through martial arts discipline. Arcane Skill: Focus (Spirit). Starting Powers: 1, Power Points: 15. Requires the Martial Artist Edge as well (two-Edge investment). Available powers: Boost/Lower Trait, Deflection, Healing, Warrior\'s Gift, and more. Represents Asian kung fu traditions and other disciplines.',
        summary: 'Martial arts chi powers (15 PP, 1 power, needs Martial Artist)' },

      // --- Professional Edges ---
      { id: 'dl_agent', name: 'Agent', category: 'Professional', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'skill', skill: 'fighting', minimum: 6 }, { type: 'skill', skill: 'occult', minimum: 6 }, { type: 'skill', skill: 'shooting', minimum: 6 }],
        description: 'You work for the Agency, the U.S. government\'s secret supernatural investigation branch. You receive a Gatling pistol, a badge, a monthly stipend ($40+), and can call in Favors from the organization. You investigate abominations and cover up the truth.',
        summary: 'Agency operative with Gatling pistol & Favors' },
      { id: 'dl_ranger', name: 'Territorial Ranger', category: 'Professional', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 6 }, { type: 'skill', skill: 'fighting', minimum: 6 }, { type: 'skill', skill: 'intimidation', minimum: 6 }, { type: 'skill', skill: 'riding', minimum: 6 }, { type: 'skill', skill: 'shooting', minimum: 6 }],
        description: 'You\'re a law enforcement officer patrolling the uncontrolled territories, handling both mundane outlaws and supernatural threats. You receive an armored duster, a rifle, a horse, a badge, and can call in Favors.',
        summary: 'Frontier lawman with gear & Favors' },

      // --- Combat & Weird Edges ---
      { id: 'dl_bornSaddle', name: 'Born in the Saddle', category: 'Combat', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'riding', minimum: 6 }],
        description: '+2 to Riding rolls. Your mount\'s Pace increases by +2 and its running die increases one step. Essential for any frontier rider.',
        summary: '+2 Riding, +2 mount Pace' },
      { id: 'dl_gallowsHumor', name: 'Gallows Humor', category: 'Weird', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'taunt', minimum: 6 }],
        description: 'Use Taunt instead of Spirit when making a Fear check. On a raise, provide +1 Support to all allies making the same Fear check. Laugh in the face of horror.',
        summary: 'Taunt for Fear checks, support allies' },
      { id: 'dl_taleTeller', name: 'Tale-Teller', category: 'Weird', rank: 'Novice',
        requirements: [{ type: 'skill_any', skills: ['performance', 'persuasion'], minimum: 8 }],
        description: 'Tell tales of heroic deeds to grant listeners Conviction (add d6 to a trait or damage roll, explodes). Successful storytelling can also reduce local Fear Levels by spreading hope.',
        summary: 'Stories grant Conviction, reduce Fear Levels' },
      { id: 'dl_knack', name: 'Knack', category: 'Weird', rank: 'Novice',
        requirements: [],
        description: 'Character creation only. You were born under unusual circumstances that grant a minor supernatural gift. Options include: Born on Christmas (resist evil arcane effects), Seventh Son (sense supernatural), Breech Birth (see invisible), Born on All Hallows Eve (communicate with spirits), and more. Work with your Marshal to pick one.',
        summary: 'Birth-given supernatural gift (creation only)' },
      { id: 'dl_veteranWW', name: 'Veteran o\' the Weird West', category: 'Weird', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 6 }, { type: 'skill', skill: 'occult', minimum: 6 }],
        description: 'You\'ve seen things that would break lesser folk. You\'ve survived encounters with the walking dead, wendigos, and worse. +2 to resist Fear effects and +1 to Soak rolls against supernatural attacks.',
        summary: '+2 vs Fear, +1 Soak vs supernatural' },
      { id: 'dl_quickDraw', name: 'Quick Draw', category: 'Combat', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
        description: 'Draw an additional Action Card when spending a Benny. Essential for fast-drawing gunslingers who live and die by speed.',
        summary: 'Extra Action Card when spending Benny' },
    ],

    HINDRANCES: [
      { id: 'dl_ailinMinor', name: 'Ailin\' (Minor)', type: 'Minor', description: 'Frontier disease or chronic condition. -2 to resist Fatigue from sickness and environmental effects. A Critical Failure on such a roll means conditions worsen.' },
      { id: 'dl_ailinMajor', name: 'Ailin\' (Major)', type: 'Major', description: 'Severe frontier disease. -2 to resist Fatigue effects. A Critical Failure means death. The Weird West is no place for the sickly.' },
      { id: 'dl_heavySleeper', name: 'Heavy Sleeper', type: 'Minor', description: 'You sleep like the dead (hopefully not literally). -4 to Notice rolls to wake up. Ambushes and night raids are your worst nightmare.' },
      { id: 'dl_oldWaysMinor', name: 'Old Ways Oath (Minor)', type: 'Minor', description: 'You pledge to honor the old traditions and avoid modern technology. Gain a free reroll on Spirit rolls while faithful. Violating the vow withdraws the benefit for 24 hours.' },
      { id: 'dl_oldWaysMajor', name: 'Old Ways Oath (Major)', type: 'Major', description: 'Mandatory for Shamans (taken for free). Strict adherence to tradition \u2014 cannot use ghost rock devices or mass-produced goods without suffering Fatigue. Free Spirit reroll while faithful.' },
      { id: 'dl_cursed', name: 'Cursed', type: 'Major', description: 'Past sins or dark affiliations bring cosmic bad luck. For each character with Cursed, the Marshal starts with one additional Benny to use against the posse. The universe is out to get you.' },
      { id: 'dl_grimServant', name: 'Grim Servant o\' Death', type: 'Major', description: 'Wild Cards only. Adds +1 to every damage roll you make, regardless of source. But on a Critical Failure attack roll, you hit the nearest ally with a raise. Death follows in your wake.' },
      { id: 'dl_tenderfoot', name: 'Tenderfoot', type: 'Minor', description: 'Extra sensitivity to pain. Suffer an additional -1 penalty while Wounded (stacks with normal wound penalties). The Weird West will toughen you up \u2014 or kill you trying.' },
    ],

    GEAR: {
      melee: [
        { id: 'dl_bowie', name: 'Bowie Knife', damage: 'Str+d4+1', cost: 3, weight: 1, notes: 'AP 1' },
        { id: 'dl_tomahawk', name: 'Tomahawk', damage: 'Str+d6', cost: 5, weight: 2, notes: 'Can be thrown (3/6/12)' },
        { id: 'dl_saber', name: 'Cavalry Saber', damage: 'Str+d6', cost: 15, weight: 3, notes: '+1 Parry when mounted' },
        { id: 'dl_warClub', name: 'War Club', damage: 'Str+d6', cost: 3, weight: 3, notes: '' },
        { id: 'dl_pickaxe', name: 'Pickaxe', damage: 'Str+d6', cost: 5, weight: 5, notes: 'AP 1 vs rigid armor' },
        { id: 'dl_whip', name: 'Whip', damage: 'Str+d4', cost: 5, weight: 2, notes: 'Reach 2, can Entangle' },
      ],
      ranged: [
        { id: 'dl_peacemaker', name: 'Colt Peacemaker (.45)', damage: '2d6+1', range: '12/24/48', cost: 15, weight: 2, notes: 'AP 1, Revolver, 6 shots' },
        { id: 'dl_thunderer', name: 'Colt Thunderer (.41)', damage: '2d6', range: '12/24/48', cost: 13, weight: 2, notes: 'AP 1, Revolver, 6 shots' },
        { id: 'dl_schofield', name: 'S&W Schofield (.45)', damage: '2d6+1', range: '12/24/48', cost: 15, weight: 2, notes: 'AP 1, Revolver, 6 shots' },
        { id: 'dl_derringer', name: 'Derringer (.41)', damage: '2d6', range: '5/10/20', cost: 5, weight: 1, notes: '2 shots, easily concealed' },
        { id: 'dl_winchester', name: 'Winchester \'73 (.44)', damage: '2d8-1', range: '24/48/96', cost: 25, weight: 5, notes: 'AP 2, 15 shots' },
        { id: 'dl_sharps', name: 'Sharps Big 50 (.50)', damage: '2d10', range: '30/60/120', cost: 30, weight: 8, notes: 'AP 2, 1 shot, Snapfire' },
        { id: 'dl_coachGun', name: 'Double-Barrel Shotgun', damage: '1-3d6', range: '12/24/48', cost: 12, weight: 6, notes: '2 shots, see shotgun rules' },
        { id: 'dl_gatlingPistol', name: 'Gatling Pistol', damage: '2d6+1', range: '12/24/48', cost: 400, weight: 5, notes: 'RoF 3, AP 1, 12 shots, ghost rock powered' },
        { id: 'dl_bow', name: 'Plains Bow', damage: 'Str+d6', range: '12/24/48', cost: 5, weight: 2, notes: '' },
        { id: 'dl_dynamite', name: 'Dynamite Stick', damage: '2d6', range: '3/6/12', cost: 3, weight: 1, notes: 'MBT, 1 round fuse' },
      ],
      armor: [
        { id: 'dl_duster', name: 'Armored Duster', armor: 1, cost: 25, weight: 5, notes: 'Covers torso, arms, legs', coverage: 'Torso, Arms, Legs' },
        { id: 'dl_breastplate', name: 'Breastplate', armor: 2, cost: 40, weight: 10, notes: 'Covers torso only', coverage: 'Torso' },
        { id: 'dl_ghostSteel', name: 'Ghost Steel Vest', armor: 3, cost: 200, weight: 6, notes: 'Covers torso. Ghost rock-forged.', coverage: 'Torso' },
      ],
      mundane: [
        { id: 'dl_lasso', name: 'Lasso (Lariat)', cost: 2, weight: 2, notes: 'Range 3, Athletics to grapple' },
        { id: 'dl_ghostRock', name: 'Ghost Rock (1 lb)', cost: 100, weight: 1, notes: 'Screams when burned. Fuel for mad science.' },
        { id: 'dl_holyWater', name: 'Holy Water (vial)', cost: 5, weight: 0.5, notes: '2d4 damage to undead/demons' },
        { id: 'dl_silverBullets', name: 'Silver Bullets (6)', cost: 5, weight: 0.5, notes: 'Bypass werewolf invulnerability' },
        { id: 'dl_horseTack', name: 'Horse & Tack', cost: 150, weight: 0, notes: 'Pace 10, d8 running die' },
        { id: 'dl_tarotDeck', name: 'Huckster\'s Tarot Deck', cost: 5, weight: 0.5, notes: 'Required focus for Huckster hexes' },
        { id: 'dl_medicBag', name: 'Frontier Doctor\'s Bag', cost: 25, weight: 3, notes: '+1 to Healing' },
        { id: 'dl_ghostPowderAmmo', name: 'Ghost-Powder Ammo (6)', cost: 10, weight: 0.5, notes: '+1 Damage, +1 AP. 10x normal ammo cost.' },
        { id: 'dl_trailRations', name: 'Trail Rations (1 week)', cost: 5, weight: 5, notes: 'Jerky, hardtack, and beans' },
        { id: 'dl_bedroll', name: 'Bedroll & Blanket', cost: 5, weight: 4, notes: '' },
        { id: 'dl_whiskey', name: 'Bottle of Whiskey', cost: 2, weight: 1, notes: 'Liquid courage. Or trade goods.' },
        { id: 'dl_rope', name: 'Rope (20 yards)', cost: 3, weight: 5, notes: '' },
        { id: 'dl_lantern', name: 'Lantern', cost: 5, weight: 2, notes: '4" radius, 3 hours per fill' },
      ],
    },
  },

  rifts: {
    id: 'rifts',
    name: 'Rifts',
    subtitle: 'The Tomorrow Legion',
    description: 'The apocalypse came and went. Rifts in space-time tear open across the globe, unleashing monsters, magic, and alien civilizations. Mega-corporations, warlords, and the Coalition States battle for dominance. Heroes of all kinds join the Tomorrow Legion to fight back.',
    color: '#4a90d9',
    icon: '\u26A1',
    banner: 'banner-rifts.jpg',

    RACES: [
      {
        id: 'rf_human', name: 'Human',
        description: 'Survivors of the apocalypse. Humans in Rifts Earth are tough, resourceful, and often augmented with cybernetics or psychic abilities.',
        abilities: [
          { type: 'free_edge', count: 1, label: 'Adaptable', description: 'Humans begin with one free Novice Edge.' },
        ],
      },
      {
        id: 'rf_dBee', name: 'D-Bee (Dimensional Being)',
        description: 'Beings from other dimensions stranded on Rifts Earth. Varied in form, feared by the Coalition, and often persecuted.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'vigor', value: 6, label: 'Dimensional Resilience', description: 'D-Bees start with d6 Vigor from surviving dimensional travel.' },
          { type: 'ability', label: 'Alien Heritage', description: 'Choose one: Natural Armor +2, Flight Pace 6, or +1 Size/Toughness.' },
          { type: 'racial_hindrance', label: 'Outsider (Major)', description: 'Persecuted by the Coalition States. -2 Persuasion in CS territory.' },
        ],
      },
      {
        id: 'rf_cyborg', name: 'Full Conversion Cyborg',
        description: 'More machine than flesh. Full conversion borgs trade their humanity for incredible combat capability and near-indestructible bodies.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'strength', value: 8, label: 'Cybernetic Strength', description: 'Start with d8 Strength from cybernetic enhancement.' },
          { type: 'toughness_bonus', value: 4, label: 'Armored Chassis', description: '+4 Toughness from integrated armor plating.' },
          { type: 'racial_hindrance', label: 'Outsider (Minor)', description: 'Disturbing appearance. -2 Persuasion with unaugmented people.' },
          { type: 'racial_hindrance', label: 'Dependency (Power)', description: 'Must recharge power cells every 48 hours or begin losing function.' },
          { type: 'ability', label: 'Construct', description: 'Does not heal naturally. Requires Repair skill. Immune to disease and poison.' },
        ],
      },
      {
        id: 'rf_quickflex', name: 'Quick-Flex Alien',
        description: 'Lithe, fast, multi-limbed aliens prized as scouts and infiltrators. Their reflexes are nearly superhuman.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'agility', value: 8, label: 'Lightning Reflexes', description: 'Start with d8 Agility.' },
          { type: 'pace_modifier', value: 2, label: 'Swift', description: '+2 Pace from natural speed.' },
          { type: 'racial_hindrance', label: 'Outsider (Major)', description: 'Alien appearance. Hunted by Coalition forces.' },
          { type: 'size_modifier', value: -1, label: 'Small Frame', description: 'Size -1 and -1 Toughness.' },
        ],
      },
      {
        id: 'rf_dogBoy', name: 'Dog Boy',
        description: 'Coalition-engineered canine-human hybrids with psychic sensitivity. Many have escaped to join the Tomorrow Legion.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'vigor', value: 6, label: 'Hardy', description: 'Dog Boys start with d6 Vigor.' },
          { type: 'ability', label: 'Psychic Sense', description: 'Can detect supernatural beings and magic within 10" (20 yards). +2 to Notice such entities.' },
          { type: 'ability', label: 'Keen Senses', description: '+2 to Notice rolls involving smell or hearing.' },
          { type: 'racial_hindrance', label: 'Loyal', description: 'Extremely loyal to packmates. Will never abandon companions.' },
        ],
      },
    ],

    EDGES: [
      { id: 'rf_megaDamage', name: 'Mega-Damage', category: 'Rifts', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'strength', minimum: 8 }],
        description: 'Your melee attacks count as Mega-Damage. +4 AP on all melee attacks against MDC targets.',
        summary: 'Melee = Mega-Damage, +4 AP' },
      { id: 'rf_cyberneticAugment', name: 'Cybernetic Augmentation', category: 'Rifts', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 6 }],
        description: 'Embedded cybernetics grant +1 to one attribute-linked skill and +1 Toughness. Reduces healing magic effectiveness by 1.',
        summary: '+1 skill, +1 Toughness, -1 magic healing' },
      { id: 'rf_leyLineWalker', name: 'Ley Line Sense', category: 'Rifts', rank: 'Novice',
        requirements: [{ type: 'edge_any', edges: ['abMagic'] }],
        description: 'Can sense Ley Lines within 5 miles. +2 to arcane skill rolls while standing on a Ley Line.',
        summary: 'Sense Ley Lines, +2 arcane on lines' },
      { id: 'rf_juicerReflexes', name: 'Juicer Reflexes', category: 'Rifts', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }],
        description: 'Chemical augmentation grants +2 to all Agility-based rolls and initiative. Burns out in 5 years.',
        summary: '+2 Agility rolls and initiative' },
      { id: 'rf_glitterBoy', name: 'Glitter Boy Pilot', category: 'Rifts', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 6 }, { type: 'skill', skill: 'piloting', minimum: 6 }],
        description: 'Trained to pilot the legendary Glitter Boy power armor. +2 to Piloting and Shooting while in GB armor.',
        summary: '+2 Pilot/Shoot in Glitter Boy' },
      { id: 'rf_psiSword', name: 'Psi-Sword', category: 'Rifts', rank: 'Novice',
        requirements: [{ type: 'edge_any', edges: ['abPsionics'] }, { type: 'attribute', attribute: 'spirit', minimum: 8 }],
        description: 'Manifest a blade of psychic energy (Str+d8, AP 4, Mega-Damage). Costs 2 PP per scene to maintain.',
        summary: 'Psychic blade: Str+d8, AP 4, MD' },
      { id: 'rf_coalitionTraining', name: 'Coalition Military Training', category: 'Rifts', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'shooting', minimum: 6 }, { type: 'skill', skill: 'fighting', minimum: 6 }],
        description: '+1 to Shooting and Fighting rolls when working with a team. +2 to resist Intimidation.',
        summary: '+1 team combat, +2 vs Intimidation' },
      { id: 'rf_technoWizard', name: 'Techno-Wizard', category: 'Rifts', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'skill', skill: 'repair', minimum: 6 }],
        description: 'Can imbue technology with magic. Create devices that run on PPE. +2 to Repair rolls on TW devices.',
        summary: 'Magical tech creation, +2 TW Repair' },
    ],

    HINDRANCES: [
      { id: 'rf_wanted_cs', name: 'Coalition Wanted', type: 'Major', description: 'The Coalition States have you on their kill list. Dead Boy patrols and Skelebots actively hunt you.' },
      { id: 'rf_cyberTrauma', name: 'Cyber-Trauma', type: 'Minor', description: 'Cybernetic implants cause phantom pain. -1 to Spirit rolls to resist psychological stress.' },
      { id: 'rf_dimensionSick', name: 'Dimension Sickness', type: 'Minor', description: 'Passing through Rifts causes Fatigue. Must make Vigor roll or gain a level of Fatigue for 1d4 hours.' },
      { id: 'rf_juicerBurnout', name: 'Juicer Burnout', type: 'Major', description: 'Chemical augmentations are killing you. Every few months, make a Vigor roll or permanently lose a die type in an attribute.' },
      { id: 'rf_primitiveBackground', name: 'Primitive', type: 'Minor', description: 'From a low-tech dimension. -2 to use advanced technology, electronics, and vehicles.' },
      { id: 'rf_psiLeakage', name: 'Psi-Leakage', type: 'Minor', description: 'Psychic abilities bleed out uncontrollably. Nearby psychic-sensitives always know your location.' },
    ],

    GEAR: {
      melee: [
        { id: 'rf_vibroblade', name: 'Vibro-Knife', damage: 'Str+d6', cost: 400, weight: 1, notes: 'AP 4, MD' },
        { id: 'rf_vibroSword', name: 'Vibro-Sword', damage: 'Str+d8', cost: 800, weight: 3, notes: 'AP 4, MD' },
        { id: 'rf_chainSword', name: 'Chain Sword', damage: 'Str+d10', cost: 1200, weight: 6, notes: 'AP 2, MD, Two hands' },
        { id: 'rf_neuralMace', name: 'Neural Mace', damage: 'Str+d6', cost: 600, weight: 4, notes: 'Stun on raise (Vigor roll or Shaken)' },
        { id: 'rf_survivalKnife', name: 'Coalition Survival Knife', damage: 'Str+d4', cost: 50, weight: 1, notes: 'Silver-coated' },
      ],
      ranged: [
        { id: 'rf_laserPistol', name: 'Laser Pistol (Wilk\'s)', damage: '3d6', range: '15/30/60', cost: 600, weight: 2, notes: 'AP 2, MD, 20 shots' },
        { id: 'rf_laserRifle', name: 'Laser Rifle (Wilk\'s)', damage: '3d6+1', range: '30/60/120', cost: 1000, weight: 5, notes: 'AP 2, MD, 30 shots' },
        { id: 'rf_ionPistol', name: 'Ion Pistol', damage: '3d6', range: '12/24/48', cost: 500, weight: 3, notes: 'AP 4, MD, 12 shots' },
        { id: 'rf_plasmaRifle', name: 'Plasma Rifle (CS C-12)', damage: '3d8', range: '24/48/96', cost: 1500, weight: 6, notes: 'AP 4, MD, RoF 1, 20 shots' },
        { id: 'rf_railGun', name: 'Rail Gun (Portable)', damage: '3d10', range: '50/100/200', cost: 3000, weight: 15, notes: 'AP 6, MD, RoF 3, requires Str d8+' },
        { id: 'rf_boomGun', name: 'Boom Gun (Glitter Boy)', damage: '4d10', range: '100/200/400', cost: 0, weight: 0, notes: 'AP 10, MD, Integrated, 1/round' },
        { id: 'rf_grenade', name: 'Fragmentation Grenade', damage: '3d6', range: '5/10/20', cost: 100, weight: 1, notes: 'MBT, MD' },
      ],
      armor: [
        { id: 'rf_huntsman', name: 'Huntsman Light Armor', armor: 4, cost: 500, weight: 8, notes: 'MDC, Covers torso, arms, legs', coverage: 'Torso, Arms, Legs' },
        { id: 'rf_deadBoy', name: 'Coalition Dead Boy Armor', armor: 6, cost: 1200, weight: 15, notes: 'MDC, Full body, integrated comms', coverage: 'Full Body' },
        { id: 'rf_crusader', name: 'Crusader Power Armor', armor: 8, cost: 3000, weight: 30, notes: 'MDC, +2 Str, Pace 8, integrated weapons', coverage: 'Full Body' },
        { id: 'rf_enviroArmor', name: 'Environmental Body Armor', armor: 5, cost: 800, weight: 12, notes: 'MDC, Full enviro seal, 8hr air', coverage: 'Full Body' },
      ],
      mundane: [
        { id: 'rf_eCLIP', name: 'E-Clip (Standard)', cost: 25, weight: 0.5, notes: 'Universal energy ammo. Recharges in 4 hours.' },
        { id: 'rf_eclipLong', name: 'E-Clip (Long)', cost: 50, weight: 1, notes: 'Double capacity E-Clip.' },
        { id: 'rf_medKit', name: 'IRMSS Medical Kit', cost: 200, weight: 2, notes: '+2 Healing, nano-surgical suite, 10 uses' },
        { id: 'rf_radio', name: 'Secure Radio (Encrypted)', cost: 150, weight: 1, notes: '50 mile range, Coalition-encrypted' },
        { id: 'rf_rations', name: 'MRE Pack (1 week)', cost: 30, weight: 3, notes: 'Military rations. Barely edible.' },
        { id: 'rf_toolkit', name: 'Universal Toolkit', cost: 300, weight: 5, notes: '+1 to Repair, works on TW and conventional tech' },
        { id: 'rf_ppeBattery', name: 'PPE Battery', cost: 500, weight: 2, notes: 'Stores 20 PPE for Techno-Wizard devices' },
        { id: 'rf_holoMap', name: 'Holo-Map (Pre-Rifts)', cost: 100, weight: 0.5, notes: '+1 to Survival (navigation) in mapped regions' },
      ],
    },
  },

  pirates: {
    id: 'pirates',
    name: 'Pirates',
    subtitle: '50 Fathoms',
    description: 'The world of Caribdus is drowning. Three witches conjured a flood that has swallowed entire continents. Pirates, privateers, and fortune-seekers sail the rising seas, battling sea monsters, the undead, and each other for survival and treasure.',
    color: '#2eaa6e',
    icon: '\u2693',
    banner: 'banner-pirates.jpg',

    RACES: [
      {
        id: 'pi_human', name: 'Human',
        description: 'Visitors from Earth who arrived through a mystical maelstrom. Resourceful, adaptable, and often bringing knowledge of advanced seamanship.',
        abilities: [
          { type: 'free_edge', count: 1, label: 'Earthborn Ingenuity', description: 'Humans begin with one free Novice Edge.' },
        ],
      },
      {
        id: 'pi_masaquani', name: 'Masaquani',
        description: 'The native humans of Caribdus. Olive-skinned seafarers who have weathered the floods better than most. They know the shifting seas intimately.',
        abilities: [
          { type: 'ability', label: 'Sea Legs', description: '+2 to Boating rolls and balance-related Athletics checks on ships.' },
          { type: 'free_edge', count: 1, label: 'Native Knowledge', description: 'One free Novice Edge representing their cultural upbringing.' },
        ],
      },
      {
        id: 'pi_kehana', name: 'Kehana',
        description: 'Red-skinned tribal warriors from the jungles of Caribdus. Fierce fighters with natural camouflage in tropical environments.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'strength', value: 6, label: 'Strong', description: 'Kehana start with d6 Strength.' },
          { type: 'ability', label: 'Jungle Born', description: '+2 to Stealth and Survival in tropical/jungle environments.' },
          { type: 'racial_hindrance', label: 'Outsider (Minor)', description: 'Distrusted by other Caribdus races. -2 Persuasion with non-Kehana.' },
          { type: 'racial_hindrance', label: 'Illiterate', description: 'Kehana have an oral tradition. Cannot read or write without taking the appropriate Edge.' },
        ],
      },
      {
        id: 'pi_grael', name: 'Grael',
        description: 'Massive, gray-skinned brutes with incredible strength. Peaceful by nature but terrifying in battle.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'strength', value: 8, label: 'Powerful', description: 'Grael start with d8 Strength.' },
          { type: 'size_modifier', value: 1, label: 'Large', description: 'Size +1 and +1 Toughness.' },
          { type: 'racial_hindrance', label: 'All Thumbs', description: '-2 to use complex mechanisms. Grael hands are too large for fine work.' },
          { type: 'pace_set', value: 5, label: 'Slow', description: 'Pace 5, d4 running die.' },
          { type: 'run_die', value: 4 },
        ],
      },
      {
        id: 'pi_kraken', name: 'Kraken',
        description: 'Squid-like humanoids with tentacles and natural swimming ability. Ancient and wise, they are the lorekeepers of the deep.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'smarts', value: 6, label: 'Cunning', description: 'Kraken start with d6 Smarts.' },
          { type: 'ability', label: 'Aquatic', description: 'Swim Pace equal to Athletics. Cannot drown.' },
          { type: 'ability', label: 'Tentacles', description: 'Str+d4 natural attack. +2 to Grapple attempts.' },
          { type: 'racial_hindrance', label: 'Dependency (Water)', description: 'Must submerge in salt water for 1 hour per day or gain Fatigue.' },
          { type: 'racial_hindrance', label: 'Outsider (Minor)', description: 'Unsettling appearance. -2 to Persuasion in port towns.' },
        ],
      },
      {
        id: 'pi_atani', name: 'Atani',
        description: 'Mysterious, pale-skinned elven folk with an affinity for wind magic. Graceful sailors who can read the weather like a book.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'agility', value: 6, label: 'Graceful', description: 'Atani start with d6 Agility.' },
          { type: 'ability', label: 'Wind Reader', description: '+2 to Notice rolls related to weather. Can predict storms 1d6 hours in advance.' },
          { type: 'ability', label: 'Low Light Vision', description: 'See in dim and dark conditions.' },
          { type: 'racial_hindrance', label: 'Frail', description: '-1 Toughness from slender build.' },
          { type: 'toughness_bonus', value: -1, label: 'Frail', description: '-1 Toughness.' },
        ],
      },
    ],

    EDGES: [
      { id: 'pi_seaDog', name: 'Sea Dog', category: 'Pirates', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'boating', minimum: 6 }],
        description: '+2 to Boating rolls. Ignore penalties from rough seas. Crew morale +1 while under your command.',
        summary: '+2 Boating, ignore rough seas' },
      { id: 'pi_boarder', name: 'Boarder', category: 'Pirates', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }, { type: 'skill', skill: 'fighting', minimum: 6 }],
        description: '+2 to Athletics when boarding enemy vessels. Free attack against one foe when first boarding.',
        summary: '+2 boarding, free attack' },
      { id: 'pi_cannoneer', name: 'Cannoneer', category: 'Pirates', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'shooting', minimum: 8 }],
        description: '+2 to Shooting rolls with ship cannons. Reduce reload time by 1 action.',
        summary: '+2 cannon Shooting, faster reload' },
      { id: 'pi_treasureNose', name: 'Treasure Nose', category: 'Pirates', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 6 }],
        description: '+2 to Notice rolls to detect hidden treasure, secret doors, or concealed valuables.',
        summary: '+2 Notice for treasure' },
      { id: 'pi_stormCaller', name: 'Storm Caller', category: 'Pirates', rank: 'Novice',
        requirements: [{ type: 'edge_any', edges: ['abMagic', 'abMiracles', 'abGifted'] }, { type: 'attribute', attribute: 'spirit', minimum: 8 }],
        description: 'Can control wind and weather within 1 mile. +2 to arcane skill rolls for weather-based powers.',
        summary: 'Control weather, +2 weather powers' },
      { id: 'pi_seaLegs', name: 'Sea Legs', category: 'Pirates', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'agility', minimum: 6 }],
        description: 'Ignore all penalties for fighting on a moving vessel. +1 Parry while aboard a ship.',
        summary: 'No ship movement penalties, +1 Parry' },
      { id: 'pi_pirateKing', name: 'Pirate Reputation', category: 'Pirates', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }],
        description: 'Your reputation precedes you. +2 to Intimidation against sailors and merchants. Crew loyalty +1.',
        summary: '+2 Intimidation (sailors), +1 crew' },
      { id: 'pi_swimLikeAFish', name: 'Swim Like a Fish', category: 'Pirates', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'athletics', minimum: 6 }],
        description: 'Swim Pace equal to full Pace. Can hold breath for Vigor die in minutes. +2 to resist drowning.',
        summary: 'Full swim Pace, long breath' },
    ],

    HINDRANCES: [
      { id: 'pi_seasick', name: 'Seasick', type: 'Minor', description: '-1 to all rolls while on a ship in anything worse than calm seas. A pirate\'s worst shame.' },
      { id: 'pi_landLubber', name: 'Landlubber', type: 'Minor', description: '-2 to Boating rolls and Athletics checks while on ships. You just haven\'t gotten your sea legs.' },
      { id: 'pi_markedByTheDeep', name: 'Marked by the Deep', type: 'Major', description: 'Sea creatures are drawn to attack you. Krakens, sharks, and sea serpents single you out in encounters.' },
      { id: 'pi_cursedTreasure', name: 'Cursed Treasure', type: 'Major', description: 'You took something you shouldn\'t have. Bad luck follows: -1 to all Trait rolls until the curse is lifted.' },
      { id: 'pi_pegLeg', name: 'Peg Leg', type: 'Minor', description: 'Pace 5, d4 running die. -2 to Athletics involving legs. But it looks intimidating!' },
      { id: 'pi_superstitious', name: 'Superstitious', type: 'Minor', description: 'Must follow sailor superstitions (no whistling, no women aboard, etc.) or suffer -1 to all rolls from anxiety.' },
    ],

    GEAR: {
      melee: [
        { id: 'pi_cutlass', name: 'Cutlass', damage: 'Str+d6', cost: 100, weight: 2, notes: '+1 Parry aboard ships' },
        { id: 'pi_rapier', name: 'Dueling Rapier', damage: 'Str+d4', cost: 200, weight: 2, notes: 'Parry +1' },
        { id: 'pi_boardingAxe', name: 'Boarding Axe', damage: 'Str+d6', cost: 75, weight: 2, notes: '+2 to Athletics (climbing) on ships' },
        { id: 'pi_belayingPin', name: 'Belaying Pin', damage: 'Str+d4', cost: 1, weight: 1, notes: 'Improvised. Free aboard any ship.' },
        { id: 'pi_harpoon', name: 'Harpoon', damage: 'Str+d6', cost: 50, weight: 3, notes: 'Reach 1, can be thrown (3/6/12), attached rope' },
        { id: 'pi_trident', name: 'Trident', damage: 'Str+d6', cost: 120, weight: 3, notes: 'Reach 1, can be thrown (2/4/8)' },
      ],
      ranged: [
        { id: 'pi_flintlock', name: 'Flintlock Pistol', damage: '2d6+1', range: '5/10/20', cost: 150, weight: 2, notes: '1 shot, 2 actions to reload' },
        { id: 'pi_blunderbuss', name: 'Blunderbuss', damage: '1-3d6', range: '10/20/40', cost: 200, weight: 6, notes: 'Shotgun rules, 1 shot, 2 actions reload' },
        { id: 'pi_musket', name: 'Musket', damage: '2d8', range: '15/30/60', cost: 300, weight: 6, notes: '1 shot, 2 actions to reload' },
        { id: 'pi_swivel', name: 'Swivel Gun (Ship)', damage: '2d8', range: '15/30/60', cost: 500, weight: 50, notes: 'Ship-mounted, 1 shot, crew reload' },
        { id: 'pi_throwingKnives', name: 'Throwing Knives (3)', damage: 'Str+d4', range: '3/6/12', cost: 30, weight: 1, notes: '' },
        { id: 'pi_crossbow', name: 'Hand Crossbow', damage: '2d4', range: '5/10/20', cost: 150, weight: 2, notes: 'AP 1, 1 action to reload, concealable' },
      ],
      armor: [
        { id: 'pi_leatherJerkin', name: 'Leather Jerkin', armor: 1, cost: 40, weight: 5, notes: 'Covers torso', coverage: 'Torso' },
        { id: 'pi_breastplate', name: 'Conquistador Breastplate', armor: 3, cost: 400, weight: 12, notes: 'Covers torso only', coverage: 'Torso' },
        { id: 'pi_sharkHide', name: 'Sharkskin Armor', armor: 2, cost: 200, weight: 8, notes: 'Covers torso, arms. Swimable.', coverage: 'Torso, Arms' },
        { id: 'pi_seaScale', name: 'Sea Serpent Scale Mail', armor: 3, cost: 600, weight: 10, notes: 'Covers torso, arms. Rare and prized.', coverage: 'Torso, Arms' },
      ],
      shields: [
        { id: 'pi_buckler', name: 'Buckler', parryBonus: 1, cost: 30, weight: 2, notes: 'Light enough for ship combat' },
        { id: 'pi_roundShield', name: 'Round Shield', parryBonus: 2, cost: 80, weight: 6, notes: '' },
      ],
      mundane: [
        { id: 'pi_spyglass', name: 'Spyglass', cost: 100, weight: 1, notes: '+2 to Notice at long range' },
        { id: 'pi_compass', name: 'Compass', cost: 50, weight: 0.5, notes: '+1 to Boating (navigation)' },
        { id: 'pi_grapple', name: 'Grappling Hook & Rope', cost: 50, weight: 4, notes: 'Essential for boarding' },
        { id: 'pi_rum', name: 'Barrel of Rum (10 servings)', cost: 30, weight: 15, notes: 'Crew morale. Trade goods. Liquid courage.' },
        { id: 'pi_treasureMap', name: 'Treasure Map (Dubious)', cost: 50, weight: 0, notes: 'May or may not lead to actual treasure...' },
        { id: 'pi_divingBell', name: 'Diving Bell (Portable)', cost: 200, weight: 20, notes: '30 minutes of underwater air' },
        { id: 'pi_fishingNet', name: 'Fishing Net', cost: 10, weight: 3, notes: 'Food source. Can also entangle (3/6/12)' },
        { id: 'pi_sextant', name: 'Sextant', cost: 150, weight: 1, notes: '+2 to navigation on open seas' },
        { id: 'pi_healersKit', name: 'Ship Surgeon\'s Kit', cost: 100, weight: 3, notes: '+2 to Healing, 5 uses' },
        { id: 'pi_waterBarrel', name: 'Fresh Water Barrel', cost: 5, weight: 40, notes: '1 week supply for 4 crew' },
      ],
    },
  },

  pathfinder: {
    id: 'pathfinder',
    name: 'Pathfinder',
    subtitle: 'Savage Pathfinder',
    description: 'The world of Golarion awaits — a realm of ancient empires, forgotten dungeons, and powerful magic, adapted for the fast, furious, and fun rules of Savage Worlds. From the streets of Absalom to the depths of the Darklands, heroes rise to battle gods, demons, and dragons.',
    color: '#7b2d8e',
    icon: '⚔',
    banner: 'banner-pathfinder.jpg',

    RACES: [
      {
        id: 'pf_human', name: 'Human',
        description: 'The most versatile and ambitious of the civilized races. Humans dominate Golarion through sheer adaptability, filling every role from warrior to wizard.',
        abilities: [
          { type: 'free_edge', count: 1, label: 'Adaptable', description: 'Humans begin with one free Novice Edge of their choice.' },
        ],
      },
      {
        id: 'pf_elf', name: 'Elf',
        description: 'Ancient and graceful, elves are attuned to the natural world and the arcane arts. They returned to Golarion from the refuge of Sovyrian after Earthfall.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'agility', value: 6, label: 'Agile', description: 'Elves start with d6 Agility.' },
          { type: 'ability', label: 'Low Light Vision', description: 'Elves can see in dim and dark conditions, ignoring penalties for Dim and Dark lighting.' },
          { type: 'ability', label: 'Keen Senses', description: '+2 to Notice rolls.' },
          { type: 'racial_hindrance', label: 'Frail', description: '-1 Toughness from slender, delicate frames.' },
          { type: 'toughness_bonus', value: -1, label: 'Frail', description: '-1 Toughness.' },
        ],
      },
      {
        id: 'pf_dwarf', name: 'Dwarf',
        description: 'Stout and enduring, dwarves carved their kingdoms beneath the mountains of Golarion. They are master smiths, fierce warriors, and stubborn as stone.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'vigor', value: 6, label: 'Tough', description: 'Dwarves start with d6 Vigor.' },
          { type: 'ability', label: 'Low Light Vision', description: 'Dwarves can see in dim and dark conditions, ignoring penalties for Dim and Dark lighting.' },
          { type: 'ability', label: 'Steady Stride', description: 'Pace 5, but Pace is not further reduced by armor or encumbrance.' },
          { type: 'ability', label: 'Poison Resistant', description: '+2 to rolls to resist poison and poisoned effects.' },
          { type: 'pace_set', value: 5, label: 'Steady Stride', description: 'Pace 5 (not reduced by armor or encumbrance).' },
        ],
      },
      {
        id: 'pf_halfling', name: 'Halfling',
        description: 'Small but spirited, halflings thrive in the nooks and crannies of Golarion. Their luck is legendary, and their courage surprises those who underestimate them.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'agility', value: 6, label: 'Agile', description: 'Halflings start with d6 Agility.' },
          { type: 'size_modifier', value: -1, label: 'Small', description: 'Size -1 and -1 Toughness due to small stature.' },
          { type: 'free_edge', count: 1, label: 'Lucky', description: 'Halflings begin with the Luck Edge for free.' },
          { type: 'ability', label: 'Spirited', description: '+1 to Spirit rolls from natural resilience and determination.' },
          { type: 'toughness_bonus', value: -1, label: 'Small', description: '-1 Toughness from small size.' },
        ],
      },
      {
        id: 'pf_halforc', name: 'Half-Orc',
        description: 'Born between two worlds, half-orcs combine orcish ferocity with human cunning. They fight harder to prove themselves, whether in the arena or on the battlefield.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'strength', value: 6, label: 'Strong', description: 'Half-Orcs start with d6 Strength.' },
          { type: 'ability', label: 'Infravision', description: 'Half-Orcs can see heat signatures, halving penalties for Dim and Dark lighting.' },
          { type: 'racial_hindrance', label: 'Outsider (Minor)', description: 'Distrusted by many civilized societies. -2 Persuasion with those who distrust orcs.' },
          { type: 'ability', label: 'Intimidating', description: '+2 to Intimidation rolls.' },
        ],
      },
      {
        id: 'pf_gnome', name: 'Gnome',
        description: 'Curious and eccentric, gnomes were originally fey creatures drawn to Golarion by its wonders. They must seek constant stimulation or risk fading into the Bleaching.',
        abilities: [
          { type: 'attribute_minimum', attribute: 'smarts', value: 6, label: 'Clever', description: 'Gnomes start with d6 Smarts.' },
          { type: 'size_modifier', value: -1, label: 'Small', description: 'Size -1 and -1 Toughness due to small stature.' },
          { type: 'ability', label: 'Obsessive', description: '+2 to one Knowledge skill of their choice, reflecting their deep obsessions.' },
          { type: 'ability', label: 'Low Light Vision', description: 'Gnomes can see in dim and dark conditions, ignoring penalties for Dim and Dark lighting.' },
          { type: 'toughness_bonus', value: -1, label: 'Small', description: '-1 Toughness from small size.' },
        ],
      },
    ],

    EDGES: [
      { id: 'pf_arcaneArcher', name: 'Arcane Archer', category: 'Pathfinder', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'shooting', minimum: 6 }, { type: 'edge_any', edges: ['abMagic', 'abMiracles', 'abGifted'] }],
        description: 'Can channel spells through arrows, combining ranged attacks with arcane power. Spellcasting attacks via bow use Shooting.',
        summary: 'Channel spells through arrows' },
      { id: 'pf_paladinSmite', name: 'Paladin\'s Smite', category: 'Pathfinder', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }, { type: 'edge_any', edges: ['abMiracles'] }],
        description: '+2 damage against evil creatures and undead. Can sense evil intent within 5" as a free action.',
        summary: '+2 dmg vs evil, sense evil' },
      { id: 'pf_dragonDisciple', name: 'Dragon Disciple', category: 'Pathfinder', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'vigor', minimum: 8 }, { type: 'edge_any', edges: ['abMagic'] }],
        description: 'Draconic heritage manifests physically. Grow claws (Str+d6 natural weapon), +2 Toughness, and gain resistance to fire damage.',
        summary: 'Claws Str+d6, +2 Tough, fire resist' },
      { id: 'pf_bardicLore', name: 'Bardic Lore', category: 'Pathfinder', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 6 }, { type: 'skill', skill: 'persuasion', minimum: 6 }],
        description: '+2 to Common Knowledge rolls. Once per scene, inspire allies with a tale or song, granting them +1 to their next Trait roll.',
        summary: '+2 CK, inspire allies 1/scene' },
      { id: 'pf_rangersQuarry', name: 'Ranger\'s Quarry', category: 'Pathfinder', rank: 'Novice',
        requirements: [{ type: 'skill', skill: 'survival', minimum: 6 }, { type: 'skill', skill: 'tracking', minimum: 6 }],
        description: 'As an action, designate one target as your quarry. Gain +2 to attack and damage rolls against that target until the encounter ends.',
        summary: 'Mark quarry for +2 atk/dmg' },
      { id: 'pf_rogueSneakAttack', name: 'Rogue\'s Sneak Attack', category: 'Pathfinder', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'agility', minimum: 8 }, { type: 'skill', skill: 'stealth', minimum: 6 }],
        description: 'When attacking from behind or while flanking, deal an additional +d6 damage. The target must be unaware or engaged with an ally.',
        summary: '+d6 dmg from behind/flanking' },
      { id: 'pf_channelDivinity', name: 'Channel Divinity', category: 'Pathfinder', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'spirit', minimum: 8 }, { type: 'edge_any', edges: ['abMiracles'] }],
        description: 'Channel divine energy to heal allies or harm undead in a Medium Blast Template. Healing restores 1 Wound; harming deals 2d6 to undead.',
        summary: 'Heal or harm with divine energy (area)' },
      { id: 'pf_arcaneBond', name: 'Arcane Bond', category: 'Pathfinder', rank: 'Novice',
        requirements: [{ type: 'attribute', attribute: 'smarts', minimum: 8 }, { type: 'edge_any', edges: ['abMagic'] }],
        description: 'Bond with an item or familiar. Recover 1 extra Power Point per hour when in contact with the bonded object or companion.',
        summary: 'Bonded item/familiar, extra PP recovery' },
    ],

    HINDRANCES: [
      { id: 'pf_cursedBloodline', name: 'Cursed Bloodline', type: 'Major', description: 'Sorcerous ancestry taints your magic. On a Critical Failure with arcane skills, a wild surge occurs — the GM draws from a table of chaotic magical effects.' },
      { id: 'pf_oathBound', name: 'Oath Bound', type: 'Major', description: 'Sworn to a sacred code (paladin oath, druidic vow, monastic discipline). Breaking the code causes loss of all arcane powers until atonement is made.' },
      { id: 'pf_hauntedByUndead', name: 'Haunted by Undead', type: 'Minor', description: 'Undead can sense your life force more strongly than others. They prioritize attacking you, and you suffer -2 to Stealth rolls against undead creatures.' },
      { id: 'pf_arcaneSensitivity', name: 'Arcane Sensitivity', type: 'Minor', description: 'Proximity to magic causes splitting headaches and disorientation. -1 to resist magical effects and arcane-based attacks.' },
      { id: 'pf_dragonFear', name: 'Dragon Fear', type: 'Minor', description: 'An instinctive dread of dragonkind grips your heart. -2 to Fear checks when encountering dragons and dragon-kin.' },
      { id: 'pf_wantedThievesGuild', name: 'Wanted by the Thieves\' Guild', type: 'Major', description: 'You crossed the wrong people. The Thieves\' Guild has placed a price on your head. Assassins and bounty hunters pursue you relentlessly.' },
    ],

    GEAR: {
      melee: [
        { id: 'pf_longsword', name: 'Longsword', damage: 'Str+d8', cost: 300, weight: 3, notes: '' },
        { id: 'pf_greatsword', name: 'Greatsword', damage: 'Str+d10', cost: 500, weight: 6, notes: 'Two hands' },
        { id: 'pf_battleaxe', name: 'Battleaxe', damage: 'Str+d8', cost: 250, weight: 4, notes: 'AP 1' },
        { id: 'pf_rapier', name: 'Rapier', damage: 'Str+d4', cost: 200, weight: 2, notes: 'Parry +1' },
        { id: 'pf_warHammer', name: 'War Hammer', damage: 'Str+d6', cost: 250, weight: 3, notes: 'AP 1 vs rigid armor' },
        { id: 'pf_dagger', name: 'Dagger', damage: 'Str+d4', cost: 25, weight: 1, notes: '' },
        { id: 'pf_staff', name: 'Staff', damage: 'Str+d4', cost: 10, weight: 3, notes: 'Parry +1, Reach 1' },
        { id: 'pf_glaive', name: 'Glaive', damage: 'Str+d8', cost: 300, weight: 5, notes: 'Reach 1, two hands' },
      ],
      ranged: [
        { id: 'pf_longbow', name: 'Longbow', damage: '2d6', range: '15/30/60', cost: 200, weight: 2, notes: '' },
        { id: 'pf_shortbow', name: 'Shortbow', damage: '2d6', range: '12/24/48', cost: 100, weight: 1, notes: '' },
        { id: 'pf_lightCrossbow', name: 'Light Crossbow', damage: '2d6', range: '15/30/60', cost: 200, weight: 3, notes: 'AP 2, 1 action to reload' },
        { id: 'pf_heavyCrossbow', name: 'Heavy Crossbow', damage: '2d8', range: '15/30/60', cost: 400, weight: 5, notes: 'AP 2, 2 actions to reload' },
        { id: 'pf_throwingAxes', name: 'Throwing Axes', damage: 'Str+d6', range: '3/6/12', cost: 75, weight: 2, notes: '' },
        { id: 'pf_sling', name: 'Sling', damage: 'Str+d4', range: '4/8/16', cost: 5, weight: 1, notes: '' },
      ],
      armor: [
        { id: 'pf_leatherArmor', name: 'Leather Armor', armor: 1, cost: 50, weight: 8, notes: 'Covers torso, arms, legs', coverage: 'Torso, Arms, Legs' },
        { id: 'pf_chainMail', name: 'Chain Mail', armor: 2, cost: 200, weight: 15, notes: 'Covers torso, arms, legs', coverage: 'Torso, Arms, Legs' },
        { id: 'pf_scaleMail', name: 'Scale Mail', armor: 2, cost: 300, weight: 20, notes: 'Covers torso, arms, legs. +1 armor vs piercing', coverage: 'Torso, Arms, Legs' },
        { id: 'pf_plateMail', name: 'Plate Mail', armor: 3, cost: 500, weight: 25, notes: 'Full body protection', coverage: 'Full Body' },
        { id: 'pf_mithralChain', name: 'Mithral Chain', armor: 3, cost: 1500, weight: 8, notes: 'Full body, lightweight', coverage: 'Full Body' },
        { id: 'pf_shieldRound', name: 'Shield (Round)', parryBonus: 2, cost: 50, weight: 6, notes: '+2 Parry', coverage: '' },
      ],
      mundane: [
        { id: 'pf_healingPotion', name: 'Healing Potion', cost: 50, weight: 0.5, notes: 'Restores 1 Wound when consumed' },
        { id: 'pf_torch', name: 'Torch', cost: 1, weight: 1, notes: '1 hour light, 4" radius' },
        { id: 'pf_rope', name: 'Rope (50 ft)', cost: 5, weight: 5, notes: '' },
        { id: 'pf_thievesTools', name: 'Thieves\' Tools', cost: 100, weight: 1, notes: '+2 to Lockpicking rolls' },
        { id: 'pf_holySymbol', name: 'Holy Symbol', cost: 25, weight: 1, notes: 'Required focus for divine casting' },
        { id: 'pf_spellPouch', name: 'Spell Component Pouch', cost: 50, weight: 2, notes: 'Required focus for arcane casting' },
        { id: 'pf_adventurersKit', name: 'Adventurer\'s Kit', cost: 15, weight: 8, notes: 'Bedroll, rations, waterskin, flint & steel' },
        { id: 'pf_antitoxin', name: 'Antitoxin Vial', cost: 50, weight: 0.5, notes: '+2 vs poison for 1 hour' },
        { id: 'pf_scrollCase', name: 'Scroll Case', cost: 5, weight: 1, notes: 'Waterproof scroll storage' },
        { id: 'pf_healersKit', name: 'Healer\'s Kit', cost: 50, weight: 3, notes: '+2 to Healing rolls, 5 uses' },
      ],
    },
  },
};
